### ISSUE TITLE
SO - consistent timing events for order cycles

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1051]
### Overview

Once we have Standing Orders, order cycle open and close times will be used as markers around which logic for messaging and order finalisation will be organised. This means that we want to only allow order cycles that have standing orders to open once and to close once.
### Tasks
- [ ] Opens At date for Order Cycles with Standing Orders cannot be altered once the OC is open
- [ ] Closes At date for Order Cycles with Standing Orders cannot be altered once the OC has closed
##### Other things to think about
- [ ] Should OC "open" events be triggered when an OC is created with an Opens At date that is in the past? Should we put a restriction on how far in the past this can be?
- [ ] Should OC "close" events be triggered when an OC is created with a Closes At date that is in the past? Should this be allowed at all?

**Comment by daniellemoorhead** [comment]
No longer required according to @oeoeaio
