### ISSUE TITLE
Basic ‘White Label’ Feature Set for Shopfronts

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#10555]
## Delivery Stage

- [x] Initial proposal
- [x] Agree high level specification, broken into estimatable parts
- [x] Intial dev estimates & budgets
- [x] Funding Confirmed
- [x] Create issues and prioritise for delivery

## Which type of users does this problem affect (and how many, if known)?
Particularly networks of Hubs that want shoppers to be navigating and moving around through their network rather than wandering off into the giant Open Food Network one

## Initial Proposal

Initial proposal is outlined [here](https://community.openfoodnetwork.org/t/basic-white-label-feature-set-for-shopfronts/2767)

## High Level Specification

See discourse post linked above with estimates.

## Estimates and funding partners
5 x papercuts and a slightly larger piece (which brings in reactive rails editor also wanted in other parts of the app). Discussions with @mkllnk indicate that all these pieces are quite small and straightforward. There are questions as to whether we should pick up and sort out some tech debt / architecture as we go, which would affect the scope (visual regression testing and intro of new reactive rails editor)

AU confirmed:  $6,700 AUD

## Connected wishlist and discovery discussions
https://community.openfoodnetwork.org/t/basic-white-label-feature-set-for-shopfronts/2767

**Comment by RachL** [comment]
Closing cf https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1688562957990209
