### ISSUE TITLE
[BUU] Pagination tweaks

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#10878]
## Context
This issue polishes the UI for https://github.com/openfoodfoundation/openfoodnetwork/issues/10877

## Tasks

- [x] increase padding top to be 20px
- [x] increase padding bottom to be 28px
- [x] increase distance between arrows and numbers to be 36px
- [x] increase distance between numbers to be 8px
- [x] font weight to be 600
- [x] change not selected font color to $near-black, also for arrows
- [x] update on hover as per designs attached
- [x] remove white background from dots as per designs (distance from previous and next should be 8px)
- [x] hide arrow buttons for when first or last page are loaded
- [x] hide pagination for single page catalogue
- [x] following [Pagy's docs](https://ddnexus.github.io/pagy/docs/how-to/#control-the-page-links), I'd say to change the size variable to [1,2,2,1], at the moment it becomes extremely long for big catalogues, see screenshot below with the default [1,4,4,1]

<img width="753" alt="Screenshot 2023-08-07 at 16 31 40" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/89481244-a4e5-4a04-8a43-226232dd8d64">

Question: are we using the Fontawesome icons for the arrows? It's a bit hard to tell.

## Design files
https://www.figma.com/file/v1zbrWDZSRd3Nqoe0SJ2Sm/Engineering-Delivery---Back-Office?type=design&node-id=550%3A4374&mode=design&t=5U46fvJD0fG8K6FF-1

**Comment by RachL** [comment]
@mariocarabotta @jibees this is done now, correct? 

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/0be147e8-1f42-4d2c-92c3-5fbd81d58d11)

**Comment by jibees** [comment]
Yes, this is actually done _automatically_ via pagy (our pagination tool) but maybe @mariocarabotta wants to review it (and change a bit how it is done) ?

**Comment by mariocarabotta** [comment]
thanks for checking. I'd like to have a quick look at it before we move it to done!

**Comment by mariocarabotta** [comment]
I have updated this issue with some UI tweaks, some specific scenarios and a change in Pagy's number of pages to be displayed. This is now ready for dev
