### ISSUE TITLE
Review and migrate legacy checkout specs

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/openfoodnetwork#10958]
Follow on from enabling split checkout and, 
 - https://github.com/openfoodfoundation/openfoodnetwork/pull/10913

We've removed the legacy checkout code, but there are still 12 specs that have been disabled as `pending` and need to be considered for migration to the new split checkout process. (see https://github.com/openfoodfoundation/openfoodnetwork/pull/10913/files/32b8d7201af4effc892f330848984d1f1db1ed05..9e6a7b2f8f51bf7f984339a8b3590757e026d9d6 )
- [x] spec/requests/checkout/failed_checkout_spec.rb (#12417)
- [ ] spec/requests/checkout/stripe_sca_spec.rb
- [x] spec/system/consumer/multilingual_spec.rb (#12421)
- [x] spec/system/consumer/shopping/checkout_paypal_spec.rb  https://github.com/openfoodfoundation/openfoodnetwork/pull/12494
- [x] spec/system/consumer/shopping/checkout_spec.rb (#12423)
- [ ] spec/system/consumer/shopping/checkout_stripe_spec.rb
- [x] spec/system/consumer/shopping/variant_overrides_spec.rb https://github.com/openfoodfoundation/openfoodnetwork/pull/12464

There is also a concurrency spec that was removed, but could be re-instated and updated for the split checkout controller (see https://github.com/openfoodfoundation/openfoodnetwork/pull/10913/files/e4aaecb3d49136e162f3e961a360c47f83673766..73ed3c733a9d60a535cbcc2cdcf02147c0e2d5ce )
- [x] spec/requests/checkout/concurrency_spec.rb #12856

**Comment by dacook** [comment]
We probably should have done this before fully instating the split_checkout toggle!

**Comment by RachL** [comment]
@filipefurtad0 maybe we should add this one to the roadmap candidate, what do you think?

**Comment by filipefurtad0** [comment]
Yes, indeed @RachL. There a a few tests here which need to be updated, and would be great to keep track of them in the roadmap :+1:

**Comment by sigmundpetersen** [comment]
I suggest we convert this an epic and open the individual specs as issues

**Comment by sigmundpetersen** [comment]
Hey @filipefurtad0 👋 
Added epic label and moved to Dev Ready, same as we treat the other roadmap items

**Comment by filipefurtad0** [comment]
Hey @sigmundpetersen :wave: 
Thank you for that :pray:

**Comment by filipefurtad0** [comment]
For reference: split-checkout was fully [released on v4.3.4](https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v4.3.4). The legacy-checkout controllers:

```
   # When the split_checkout feature is disabled for the current user, use the legacy checkout
  constraints FeatureToggleConstraint.new(:split_checkout, negate: true) do
    get '/checkout', to: 'checkout#edit'
    put '/checkout', to: 'checkout#update', as: :update_checkout
    get '/checkout/:state', to: 'checkout#edit', as: :checkout_state
  end
```

were replaced by the current (split-)checkout controllers:

```
  get '/checkout', to: 'checkout#edit'

  constraints step: /(details|payment|summary)/ do
    get '/checkout/:step', to: 'checkout#edit', as: :checkout_step
    put '/checkout/:step', to: 'checkout#update', as: :checkout_update
  end

  # Redirects to the new checkout for any other 'step' (ie. /checkout/cart from the legacy checkout)
  get '/checkout/:other', to: redirect('/checkout')
```

**Comment by filipefurtad0** [comment]
Most of this epic is concluded, however, I got stuck on the two last specs.

As [mentioned in delivery circle](https://community.openfoodnetwork.org/t/delivery-circle-16-jul/3164), it's best to park this issue for now. It would only make sense to have system specs for Paypal and Stripe if we could combine VCR and a proxy to redirect real calls (i.e. puffing billy, which I have not managed to implement in the past). This concerns the file:

 - spec/system/consumer/shopping/checkout_stripe_spec.rb

As for the request spec: 
- spec/requests/checkout/stripe_sca_spec.rb

I've tried to address it, [but got blocked](https://github.com/openfoodfoundation/openfoodnetwork/pull/12600/files). I'm not sure how to pass all Stripe parameters within params. So, it's perhaps not a bad idea to address this later on, although a full re-write of the spec would be needed, namely i) considering the new checkout flow and ii) replace the mock requests with real requests using VCR.

I'm unassigning myself for now.
