### ISSUE TITLE
Stripe test automation

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11890]
An epic to gather the issues we've accomplished, and the ones which are still pending so testers don't have to manually test Stripe each week / gem bump.

- Done:
- [x] [Integration/API tests] Add VCR to the stack https://github.com/openfoodfoundation/openfoodnetwork/pull/9624
- [x] [Integration/API tests] Improve payment intent tests with VCR calls https://github.com/openfoodfoundation/openfoodnetwork/pull/11742
- [x] [Integration/API tests] Extend payment intent tests i) test error responses from payment attempts made from a list of invalid cards: https://github.com/openfoodfoundation/openfoodnetwork/pull/11810
- [x] #11892
- [x] #11925
- [x] #11949
- [x] #11962
- [x] #12001
- [x] [Integration/API tests] Cards: saving cards; deleting cards ( -> covered within the folder [*/lib/stripe](https://github.com/openfoodfoundation/openfoodnetwork/issues/12001); hence marked as completed.)
- [x] #12164
- [x] #12201
- [x] #12034

- Related:

- [x] [Active Merchant] Refactor/decorator removal https://github.com/openfoodfoundation/openfoodnetwork/issues/7326
- [x] [Active Merchant] gem bump https://github.com/openfoodfoundation/openfoodnetwork/pull/11880

- To do:

~~- [ ] [System tests] Set up browser proxy + VCR for system tests: https://github.com/openfoodfoundation/openfoodnetwork/issues/8957~~
~~- [ ] [System tests] Saving cards on checkout https://github.com/openfoodfoundation/openfoodnetwork/issues/3952~~
~~- [ ] [System tests] Subscriptions (requires setting up a customer and a card)~~

- In code review:
- [x] #12409

**Comment by RachL** [comment]
@filipefurtad0 I guess you want to keep this issue open once epics are gone to track the task list? I don't think milestones are a good way to do that

**Comment by RachL** [comment]
Ok as per slack conversation, converted this one to issue again

**Comment by filipefurtad0** [comment]
While there is still a long way to go on what concerns Stripe testing, I'd say we can close this task list for now :tada:

**Comment by RachL** [comment]
KUDOS @filipefurtad0 

![ ](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZnF4ejF5dXFmMmZ1dzRzdTBpMjF1ZjQya2g1ZnppMXEyejY0MXNhaiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/wAxlCmeX1ri1y/giphy.gif)
