### ISSUE TITLE
Fix Rubocop Lint issues

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/openfoodnetwork#12330]
### Issue list

- [x] [Lint/ConstantDefinitionInBlock](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/ConstantDefinitionInBlock) (#12316)
- [x] [Lint/DuplicateBranch](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/DuplicateBranch) (#12320)
- [x] [Lint/DuplicateMethods](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/DuplicateMethods) (#12350)
- [x] [Layout/EmptyLines](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/EmptyLines)
- [x] [Lint/EmptyBlock](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/EmptyBlock)
- [x] [Lint/EmptyClass](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/EmptyClass)
- [x] [Lint/FloatComparison](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/FloatComparison)
- [x] [Lint/IneffectiveAccessModifier](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/IneffectiveAccessModifier)
- [x] [Lint/NoReturnInBeginEndBlocks](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/NoReturnInBeginEndBlocks)
- [x] [Lint/RedundantDirGlobSort](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/RedundantDirGlobSort)
- [x] [Lint/RedundantSafeNavigation](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/RedundantSafeNavigation)
- [x] [Lint/SelfAssignment](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/SelfAssignment)
- [x] [Lint/UselessMethodDefinition](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/UselessMethodDefinition)

**Comment by dacook** [comment]
Hi @anansilva , thanks for working on these tasks. I've created a sub-issue to help with tracking.

**Comment by dacook** [comment]
@sigmundpetersen , I'm not able to assign Ana to the issue. Do I need to add her to the organisation as an external collaborator, or is there a better way?

**Comment by sigmundpetersen** [comment]
Yes, to be assigned she either needs to
- be added to the organization in some way or
- comment on the issue

**Comment by dacook** [comment]
Thanks, I've invited Ana as a member as that seemed appropriate.

**Comment by anansilva** [comment]
Hi @dacook, thanks for the invite. I'm not able to assign myself to the issue, though. How can I check the list of offenses that get merged?

**Comment by dacook** [comment]
Hi @anansilva , I've assigned you now. I think you will be able to tick the boxes in the description above, or you can simply go ahead and proceed with the following one.

I noticed that the last PR was quite small. You can include more than one offence in a PR to speed things up (just make sure they are in separate commits).

**Comment by cyrillefr** [comment]
Hello @dacook,

May I work on this issue ?

**Comment by dacook** [comment]
Hi @cyrillefr , yes thanks, that would be great.
I've updated the list based on the current rubocop_todo file.

**Comment by cyrillefr** [comment]
Hello @dacook ,

With the last PR that fixes the EmptyBlock cop, it seems all issues in the list have been addresses and solved.
Hooray 😀 .

**Comment by dacook** [comment]
Woohoo! Thank you so much for your dedication Cyrille! With less tech debt weighing us down we can move quicker on new developments 🏎
