### ISSUE TITLE
[Variant tags] Ability to add several tags to a variant and filter the product list

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#13051]
⚠️ **Please use clockify code # 76  Network 2.0**

## Context

This is the first step towards adding tags to variants (ie tags which work with our tag rules). Here we want to give the ability for producers / hubs to add tags to variants in order to filter the product list.

**We need to put this work under a feature toggle, so we can reveal products tags, when we are ready to make them work with tag rules.**

## Description

**- As a:** enterprise user or super admin
**- On page:** `/admin/products`
**- I want to be able to do:** 

On the product list, I can see a new column called tags. It should be visible by default. I can create a tag by typing and pressing enter (like on the customer page) I can add as many tags as needed.

![image](https://github.com/user-attachments/assets/28066798-047c-4176-9c69-bc980409e2ab)

On the top bar, becomes then available in the dropdown, as filters.

![image](https://github.com/user-attachments/assets/11255a1e-f1bb-450b-812a-1e6e828bd7bd)

Currently the dropdown for tags, allows to see how many tag rules are linked. Making tags work with existing tag rules is going to be in another issue, but we need to think about this when choosing the type of dropdown we want to introduce here (I'm assuming we could take the opportunity to uplift this dropdown => white text when tag is selected, more rounding shapes....)

![image](https://github.com/user-attachments/assets/9c04c8c3-8f24-49ab-aa3d-98b668caa46c)

## Acceptance Criteria & Tests

See sub-issues

**Comment by rioug** [comment]
Currently we use http://mbenford.github.io/ngTagsInput/ to create the nice interface to add tags. As we are moving away from AngularJS we'll have to reproduce this functionality with StimulusJS/Turbo.

Assumption : I am assuming tag rule will be defined by an enterprise, so it makes sense to populate the dropdown with tags scoped to the supplier.  

Estimate:   
- Add tag to variant and display on bulk product screen (no editing) : **1 day**
- search by tag : **1 day**
- add editing, ie re create current interface in StimulusJS : **2-4 days**
- re styling **1 day** 

Total: 5 - 7 days 
Add 20% to cover unforeseen issues : 1 -1.4 days
**Estimations total : 6 - 8.4 days**

This is doesn't include the ability to update tags on the variant edit page, but it should be easy to add once we have a "tag interface" in place.

**Comment by RachL** [comment]
@rioug after checking with budget circle, I think we are good to go here. I'm going to create one issue per bullet point, starting with the first one, but let me know if this does not suit you.

**Comment by RachL** [comment]
@rioug do you confirm once we are through all these issues tags won't work with the existing tag rules system, we need to add an additional issue for that?

**Comment by rioug** [comment]
@RachL that's correct. The estimation doesn't include the tag rules, we will need to do additional work for that.

**Comment by rioug** [comment]
- [x] Add tag to variant and display on bulk product screen (no editing) : 1 day
- [ ] search by tag : 1 day
- [x] add editing, ie re create current interface in StimulusJS : 2-4 days
- [ ] re styling 1 day

Time update:
I currently spent 3 days on this.

**Comment by rioug** [comment]
- [x] Add tag to variant and display on bulk product screen (no editing) : 1 day
- [x] search by tag : 1 day
- [x] add editing, ie re create current interface in StimulusJS : 2-4 days
- [x] re styling 1 day

Time update:
Total dev time so far 7.5 days

**Comment by RachL** [comment]
I'm closing here: the remaining issue is to remove the feature toggle, but we can close this epic in the meantime.
