### ISSUE TITLE
Error Handling Checklist

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1439]
Ideally we will continue to add to this checklist as we note more errors that we want to be communicated...

- [ ] Datafile failed to load to end of file
- [ ] file could not be opened
- [ ] products loaded in error
- [ ] column ignored from data file
- [ ] compulsory field column missing
- [ ] user unable to update products they do not have permission to update/create
- [ ] user unable to update inventories they do not have permission to update

-- Edits --
- [ ] supplier does not exist in DB
- [ ] handling case insensitive supplier name matches...?

**Comment by Matt-Yorkley** [comment]
Added to main feature.
