### ISSUE TITLE
Stripe as a payment method - first release

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1462]
Things to test:

- [x] Check that creating a Stripe-based payment method is possible
Yes, in developer mode. Need to test creating a normal Stripe account as well.
- [x] Check that the process for connecting an Enterprise to Stripe is intuitive enough
I've only passed through Stripe setup in developer mode. But it seemed straight forward enough.
![image](https://user-images.githubusercontent.com/10843056/28600642-870ae2b2-71f6-11e7-8e71-d735e8b06c82.png)
Yay, the above are fixed.

- [x] Use some test credit cards to make payments for orders using the Stripe payment method
Have tested all the Stripe test codes (detailed [here](https://stripe.com/docs/testing#cards)). Image below shows which ones worked and which ones are not supported- but the error message has changed. Some don't get a clear error message (discovery)
![image](https://user-images.githubusercontent.com/10843056/28346047-b10c6106-6c71-11e7-88c8-eb27f733757c.png)
- [x] Store some test credit cards against a user account
![image](https://user-images.githubusercontent.com/10843056/28600585-3279ea7c-71f6-11e7-9e16-22dc364d7a44.png)

- [x] Use stored credit cards to pay for orders.
Fixed - I can save cards, and they won't save unless I ask then to save.
![image](https://user-images.githubusercontent.com/10843056/28600590-38275a22-71f6-11e7-97dd-e2844486e2b2.png)

- [x] Check that super admin Stripe enable/disable toggle works logically
Yes, it does. We may need a note to Instances saying that they need a developer to get them fully setup with Stripe. They may just be in discourse or in release notes, but a note in the backend could also be helfpul to new instances.
![image](https://user-images.githubusercontent.com/10843056/28600654-9a12193e-71f6-11e7-9b2e-7f1cb845f6a5.png)

- [x] Account interface - fixed
![image](https://user-images.githubusercontent.com/10843056/28600674-c43488fa-71f6-11e7-82eb-d2e657e4a106.png)

- [x] Keep an eye on all of the interfaces and flows and see if they make no sense

- [x] Do orders paid for with Stripe show as 'Paid'.
Yes. I can also edit these orders and they return to 'balance due' state. 
But, if an order is half paid with Stripe and the admin clicks 'add payment' they get the snail. THIS IS FIXED.
![image](https://user-images.githubusercontent.com/10843056/28600845-10c13406-71f8-11e7-941e-96ea8aad623d.png)

- [x] Can I create an order for customers from the back end? YES (just not using Stripe as payment method) FIXED
![image](https://user-images.githubusercontent.com/10843056/28601132-cda00d08-71f9-11e7-9baa-9ee859cf296b.png)

- [x] Can multiple enterprises share a Stripe payment method?
Yes, so.. A stripe payment method needs to have an enterprise as the 'stripe account owner' and this owner needs to have 'connected to stripe'.  Once it has that, it can be used by multiple enterprises (selected on the right hand side of payment method). This makes sense, because a hub may support the Stripe payments, but all buying groups also want to feed payments in. 

Yes, another scenario. The payment method can be setup where the 'Stripe Owner Account' is not one of the enterprises who is actually using the payment method. Instead it's used by another enterprise managed by the same user. E.g. below, the enterprise using the payment method doesn't own the stripe account.
![image](https://user-images.githubusercontent.com/10843056/28601415-7199c9d4-71fb-11e7-963e-af7f3d3dce1b.png)

- [x] Can transaction fees be added to Stripe payments?
Yes

**Comment by sstead** [comment]
@oeoeaio 
![image](https://user-images.githubusercontent.com/10843056/28955525-a99ffa02-792a-11e7-9fe1-2e11451835aa.png)

![image](https://user-images.githubusercontent.com/10843056/28955603-3716891e-792b-11e7-9037-69276b4aef34.png)

**Comment by simoneluijckx** [comment]
- [ ] Check that creating a Stripe-based payment method is possible
**Y:** clicking on 'connect with Stripe' leads to 'I agree' pop-up with info text
**?:** Will people be thrown back by this: "Please note that you will need to maintain your own Stripe account, pay the fees Stripe charges and handle any chargebacks and customer service yourself." --> Maybe the advantage of Stripe can be explained more? 
**Y:** Stripe-account connected (in developer mode), showed on 'Payment Methods' page

**Comment by simoneluijckx** [comment]
- [ ] Store some test credit cards against a user account
**Y:** works perfectly
![image](https://user-images.githubusercontent.com/31434588/29816930-772b4be8-8cf9-11e7-959d-1168a08b747b.png)

**Comment by simoneluijckx** [comment]
- [ ] Use stored credit cards to pay for orders
**Y:** When I'm at checkout I can choose stored credit cards or add a new card
**Y:** I can pay! 
![image](https://user-images.githubusercontent.com/31434588/29820179-f51da534-8d06-11e7-8f47-c9c09b9788d6.png)

**Comment by simoneluijckx** [comment]
- [ ] Account interface
**Y:** The order page has the correct details (incl the right date)
![image](https://user-images.githubusercontent.com/31434588/29820461-de9befb8-8d07-11e7-8a2b-fa7628f76d73.png)
**N:** When clicking on the ordernumber (or any other details page) it leads me to the order details: stating the date a month in the future
![image](https://user-images.githubusercontent.com/31434588/29820532-1d753190-8d08-11e7-9647-2b80c5e0b330.png)
**?:** Payment State 'Paid' and Shipment State 'ready' are clickable, but State 'complete' not. 

When you click 'paid' and then 'Stripe', this is what you get: 
![image](https://user-images.githubusercontent.com/31434588/29820754-dd239752-8d08-11e7-918f-5b79d51c34d8.png)

**Comment by sstead** [comment]
Some other things spotted this morning:
![image](https://user-images.githubusercontent.com/10843056/29858355-7a655aae-8da0-11e7-9dd6-cdc40ec04216.png)

![image](https://user-images.githubusercontent.com/10843056/29858356-7f9b06f4-8da0-11e7-9c39-01ce73377ac8.png)

**Comment by simoneluijckx** [comment]
Testing again, but now as a **hub**
**N:** Try to add new payment method: Stripe, but I don't get the Stripe button
Step 1: 
![image](https://user-images.githubusercontent.com/31434588/29914751-ffe32e04-8e7c-11e7-9b44-7e6e2544f062.png)
Step 2: 
![image](https://user-images.githubusercontent.com/31434588/29914790-234b7112-8e7d-11e7-89e4-5c1d532cbba5.png)
Step 3: No 'connect with Strip' button
![image](https://user-images.githubusercontent.com/31434588/29914815-37277172-8e7d-11e7-8f5b-87effdbada72.png)

**Comment by sstead** [comment]
Sorry @simoneluijckx, Stripe isn't in Staging2 anymore

**Comment by daniellemoorhead** [comment]
>Stripe isn't in Staging2 anymore

@simoneluijckx we should have it back up on staging next week if you are willing to get your hands dirty testing it again? If yes then I'll ping you when we're ready for you to test again 😄

**Comment by sstead** [comment]
testing notes:
Saving cards that are rejected.
![image](https://user-images.githubusercontent.com/10843056/30414931-17674a82-9969-11e7-84d4-6b5c53ffb64a.png)

Voids seem to work:
![image](https://user-images.githubusercontent.com/10843056/30414962-46fc61ba-9969-11e7-9f6f-a193bb76276d.png)

If not connected shouldn't be shown in the shop
![image](https://user-images.githubusercontent.com/10843056/30415208-6520f650-996a-11e7-945e-f77d97c57b27.png)

**Comment by sstead** [comment]
Testing notes
Void button disappearing when credit is owed...
![image](https://user-images.githubusercontent.com/10843056/30730757-b0166ec2-9fac-11e7-94c5-8c6f523a87be.png)
