### ISSUE TITLE
Stripe: ask customer about saving card details used in checkout

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1723]
### Overview
At the moment, we're just storing all Stripe card details used in the checkout. We need to ask whether this is what the customer wants to do.

![image](https://user-images.githubusercontent.com/10843056/28600585-3279ea7c-71f6-11e7-9e16-22dc364d7a44.png)

### Tasks
- [x] Add a 'Remember this card?' field in the stripe payments form in the checkout 
- [x] Store this flag as an instance variable on the `CreditCard` model, and use it to return early from the `create_payment_profile` callback on `payment` if saving is not requested
- [x] Create a separate flow in the StripeConnect gateway to handle processing of payments using just the original token if saving is not required (UPDATE: This was already done). :)
- [x] Specs for all of the things

**Comment by mkllnk** [comment]
I think this is all done except for one missing spec. I created a new issue for that spec: #3952. Please re-open this if you disagree.
