### ISSUE TITLE
Stripe: Improve UI around connecting a stripe account

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1727]
### Overview
A couple of improvements are required to make the process of connecting an enterprise's Stripe account to the OFN a little more intuitive.

![image](https://user-images.githubusercontent.com/10843056/28600642-870ae2b2-71f6-11e7-8e71-d735e8b06c82.png)

### Tasks
- [x] Implement hash navigation on enterprise edit page, to allow navigation to a specific tab
- [x] Use hash navigation to direct the `Connect One` button on `admin/payment_methods/stripe_connect` to the payment methods tab in the edit enterprises UI
- [x] Add a modal to handle explanation of user's responsibilities before redirecting to Stripe
