### ISSUE TITLE
Stripe: allow enterprise users to add '+ New Payment' using Stripe

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1728]
### Overview
Attempting to add a new payment to an order as an enterprise user currently causes a crash, aparently because a partial is missing. We need to allow new Stripe-based payments to be added, so we need to work out what needs to be done to allow this.

![image](https://user-images.githubusercontent.com/10843056/28600845-10c13406-71f8-11e7-941e-96ea8aad623d.png) 

![image](https://user-images.githubusercontent.com/10843056/28601132-cda00d08-71f9-11e7-9baa-9ee859cf296b.png)

### Tasks
- [x] Add templates from `spree_gateway` repo to allow viewing a payment, and creating a new payment (this fixes the snail)
- [x] Switching between payment methods in the 'new' view is broken, so fix that
- [ ] Ensure that the ability to add new payments for other payment methods has not been broken by the changes above

**Comment by oeoeaio** [comment]
I've made the decision to just fix the view so that we don't get the snail. I've created a new issue to cover the separate task of allowing the use of StripeJS to create a new Stripe-based payment from the admin section here: #1745. This is a nice-to-have for now.

**Comment by mkllnk** [comment]
Rob actually fixed this via #1745.
