### ISSUE TITLE
Standing Orders + Stripe: Restrict payment methods available to standing orders to only Cash/Cheque and Stripe

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1731]
### Overview
Payment methods other than Stripe or Cash/Cheque are not able to be 'automatically' processed, so they can't be used with standing orders. Therefore the list of payment methods that users are able to select from needs to be restricted to show only these two types, or an error if none are available.

### Tasks
- [x] Update the `shipping_and_payment_methods_ok?` method in the StandingOrdersHelper to return false unless at least one Stripe or Cash payment method is present (1 hr)
- [x] Update the explanations shown in `admin/standing_orders/setup_explanation` to reflect the restriction (0.5 hr)
- [x] Only load Cash & Stripe payment methods in the StandingOrdersController for `new` and `edit` actions (1 hr)
- [x] Add an explanation as to why only Stripe/Cash method are available to the payment method dropdown in the standing order form in `admin/standing_orders/_details` (0.5 hr)
- [x] Add validation to StandingOrderForm to prevent non Stripe/Cash payment methods from being saved against a Standing Order (0.5 hr)

**Comment by daniellemoorhead** [comment]
done, merged
