### ISSUE TITLE
Standing Orders + Stripe: Auto-process Stripe payments for standing orders when order cycle closes

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1752]
### Overview
If a standing order is using a credit card stored with Stripe to pay for each order, we need to ensure that this happens. Each standing order using Stripe should already have a card linked to it, as per #1732. The payment total on a given order should be correct as per #1751. All that remains is to make sure that the charge is being attempted, and that we can handle any failures.

### Tasks
- [x] Make sure that the existing logic in the `StandingOrderPlacementJob` is sufficient to allow a stored card to be charged successfully 
- [x] In the case of a failure, we need to fail gracefully: Allow the order to completion anyway, but mark it as unpaid and send an email to both the customer informing them of the issue.
- [ ] Also notify the shop owner when a payment fails. 
- [x] Handle the fail case where the charge fails (expired card, etc)
- [x] Handle the fail case where there is no card to charge

**Comment by daniellemoorhead** [comment]
done, merged
