### ISSUE TITLE
Stripe: use Stripe Elements instead of StripeJS

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#1755]
### Overview
It appears that in the time that we have been developing the Stripe integration for the OFN, the component that we originally selected for collection of and transmission of card details (StripeJS) has fallen out of favour somewhat. Looking over Stripe's compliance guide (https://stripe.com/docs/security#pci-dss-guidelines) it seems that compliance for sites using StripeJS with a custom form elements is more onerous to prove than for sites using Stripe's pre-built components that are served directly from Stripe ([Checkout](https://stripe.com/docs/checkout) or [Elements](https://stripe.com/docs/elements)). 

I have had a bit of a look over the docs for Elements, and I think our best bet is going to be to use it build an element for accepting card details, rather than using StripeJS. This is not as terrible as it may at first sound, the vast majority of the infrastructure we have built (100% of the backend) can remain the same. It will require a bit of work however (probably a few hours).

### Tasks
- [x] Don't use the `checkout/payments/gateway` partial for Stripe payments, build a new Stripe Elements form instead in `checkout/payments/stripe`
- [x] Update the Angular StripeJS service to use Elements instead. At first glance, I suspect this may involve creating a new service for the elements `card` object.
- [x] Make any updates that need to be made to the Angular Checkout service to allow it to submit the token returned by Elements 
- [x] Design the infrastructure so that it can be reused to store a card from the Accounts page, and then implement it there

**Comment by oeoeaio** [comment]
@stveep if you're looking for an issue to pick up and there is budget available I think you're probably best placed to have a look at this.

**Comment by daniellemoorhead** [comment]
I have a question that @stveep maybe you can answer while @oeoeaio is away - does this swap-over from .js to Element need to happen prior to launching version 1, is it on the critical path? Has the interface and connection as a new payment method already been built to allow it to go live (and therefore in use by customers) prior to swapping over?

As far as I understand @sstead has already tested it once around and Rob informed her before he went away that Maikel could stage it for her to do a final test on it...which makes me think there's something there we could push live as soon as he's back.

Over to you @stveep, would be really great if you had time to quickly check that. Or maybe @mkllnk when staging the Stripe branch for Sally could you form an opinion about this?

I've got my fingers crossed we can push what we have live ASAP, as I'm sure @lin-d-hop is as well to make many customers very happy :)

**Comment by stveep** [comment]
I don't think it's absolutely required to launch - the old API (.js v2 as we previously implemented) will still work. Rob thought the new one will be better for compliance, but it will still work. The new API (.js v3 "Elements") uses a form supplied by Stripe to enter card details and also provides CVC verification as a side effect of that. As long as your payments are actually going through without then it should be fine (it's also fairly easy to add CVC verification to the v2 flow if we need to). Almost everything in our back end code is the same, the Stripe API is just used to get an authorization token to charge a card so the end result is the same whether API v2 or v3 is used.

I have implemented v3 already and it seems to work fine but it breaks a lot of tests (basically lots checkout tests break as the credit card details form can no longer be rendered in the test environment). You can see it here:

https://github.com/stveep/openfoodnetwork/tree/stripe-elements

So I don't anticipate huge problems if we were to deploy it as v2 and swap over in the near future once Elements has been tested, and I think that any tokens obtained via the v2 API will still work when we later upgrade to v3. 

I'm not sure whether the rest of the Standing Orders functionality is ready to go, I haven't looked at it properly. It seems that things like #1751 and #1752 still need to be implemented.

**Comment by lin-d-hop** [comment]
Can stripe exist as a payment method outside of standing orders @stveep? That is exciting for a few users in itself!

**Comment by stveep** [comment]
Yes, it can be used to take credit card payments if an enterprise has connected their Stripe account to the OFN instance Stripe account (done on the admin payment methods page) - that gives the instance authorisation to charge users on the enterprise's behalf. The payments go into the enterprise Stripe account

**Comment by daniellemoorhead** [comment]
@lin-d-hop it definitely is going to be released separately to subscriptions/standing orders. That's why I asked about using v2 rather than v3 given it's already working, has been built, and should be ready to go in the next week (as long as @sstead testing doesn't break anything).
