### ISSUE TITLE
Email producers with order/delivery instructions

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#275]
1) Idea is to add subtabs to the OrderCycle tab: New Order Cycle and Manage Order Cycle.

2) Within Manage Order Cycle, manual option to send email to Single or All producers.

3) Option within producers to have email notification of orders (default to no)

4) Option to automate this upon orders closing (default to no)

5) Option within producers to have email specifying per customer order.

Summary should include:

* product
* unit
* unit cost
* quantity
* sub-total
* VAT

## Tasks

- [x] Sketch design changes to UI.
- [ ] Preferences and settings store
- [ ] Look at editable or configurable email templates
- [x] Process sending of emails
- [x] Work out how to include report content into email
- [ ] Support deployment - https://github.com/openfoodfoundation/ofn_deployment/issues/30

**Comment by NickWeir63** [comment]
When testing this  I have created a new ("July") order cycle on staging 2 which includes 6 producers.  I made sure the producer emails were coming to me and put in a test order which included products for just 2 producers (Days Cottage and Jessies Ladies).  When I click on ‘NOTIFY PRODUCERS’ it all looks good but then when the emails come through I get 6 emails all coming to ‘Nick’s test producer’ which is the first producer on the list of 6 producers on that order cycle.  None of the emails have any product details (see example below).

When I changed the email address for Days Cottage to Carol’s email and pressed the ‘NOTIFY PRODUCERS’ button again, I still got 6 blank emails to ‘Nick’s test producer’ and no email to Carol.

Please let me know if I am doing something wrong or if there is anything else I can try

Thanks 
Nick


-----Original Message-----
From: admin@openfoodweb.org [mailto:admin@openfoodweb.org] 
Sent: 13 July 2015 12:13
To: nick@stroudco.org.uk
Cc: nick@stroudco.org.uk
Subject: [Staging 2] Order cycle report

Dear Nick testing producer,

We now have all the consumer orders for next food drop. Please drop off your delivery at .
Please deliver to Stroud Valley Community School, Stroud, GL5 2HP during the regular delivery time. If this is not convenient then please call 1453840037.
Note: If you have to arrange a different delivery day and time, it is requested that you do not come on site during drop off/pick up times.

Orders summary
==============

Here is a summary of the orders for your products:


Detailed orders breakdown
=========================
Please confirm that you have got this email.
Please send me an invoice for this amount so we can send you payment.
If you need to phone on the day please call 1453840037.

Thanks and best wishes - Stroudco

**Comment by NickWeir63** [comment]
Just to let you know I am still receiving emails of this blank order summary.  So far I have received 38 of them.  They come through in batches every 3-5 hours.  Curious!

**Comment by lin-d-hop** [comment]
As a workaround to #406 there was talk on todays Skype for StroudCo to have two Hubs with the same order cycle. One hub with an outgoing fee of 12% that is hidden unless you are a member with the link; and one with 15% that is for public use.

Reports can handle this and integrate data into a single report. If the emails could handle this as well it would make for a possible work around.

Before seriously considering implementing this I would suggest a spike to see how much work it is. It would only be a workaround for now with no long term use (though that's not to say it wouldn't be a useful feature later). So if easy it might be worthwhile and if difficult it's probably not worth it.

**Comment by RohanM** [comment]
Hi everyone,

I've picked up this branch and done a bit of work on it. I noticed that producers whose products haven't been ordered still receive an email, so I've changed that so an email will only be sent if there are orders to that producer.

@NickWeir63, I wasn't able to reproduce the problems you were having, though. I've put the current version on https://staging1.openfood.com.au/ . Could you experiment and see if you can find any problems?

**Comment by NickWeir63** [comment]
Thanks @RohanM 
I edited the email addresses for a couple of the stroudco producers on staging1 - please check that I amended them in the correct place (see screenshot below)..............
![producer s email address](https://cloud.githubusercontent.com/assets/10517702/10563923/0ba8582e-7596-11e5-9ef5-29d3cdc0fc79.jpg)

.........then submitted a couple of orders for products from these producers.  I received a confirmation email to the hub (See below) but no confirmation email as a shopper and none as a producer

Hi Nick Weir, 
Well done! You have a new order for Stroudco! 
 


 
Order confirmation #R186654850 
Nick Weir <nick@nickweir.co.uk> 441453840037 
Item	Qty	Price
Veal (1kg) 
Cotswold Veal 	2 	$22.40 
Apple Juice (1L) 
Days Cottage 	2 	$1.58 
Subtotal: 	$23.97 
Shipping: 	$2.00 
Total: 	$25.97 
 
NOT PAID Payment summary 
Paying via: Cash on Collection 
Pay when you pick up 
 
Home Delivery 
Delivery on: 

  
Delivery address:
Nick Weir 
44 Bisley Road, Stroud, GL5 1HF, Tasmania 
441453840037

**Comment by RohanM** [comment]
Hi @NickWeir63,

That looks like the right place to edit the producer emails. Just checking if you edited the order cycle and clicked the "Notify Producers" button? No emails will be sent to producers until that button is pressed.

**Comment by NickWeir63** [comment]
Thanks @RohanM - that was it.  When I clicked notify producers i did receive all the correct emails to the correct addresses with the correct quantities,  However the email did not have any details under the heading "Detailed Orders Breakdown" see below
Other than that it is looking great -thanks

Dear Days Cottage,

We now have all the consumer orders for next food drop. Please drop off your delivery at .
Please deliver to Stroud Valley Community School, Stroud, GL5 2HP during the regular delivery time. If this is not convenient then please call 1453840037.
Note: If you have to arrange a different delivery day and time, it is requested that you do not come on site during drop off/pick up times.

Orders summary
==============

Here is a summary of the orders for your products:

 Days Cottage Apple Juice 1L (QTY: 7) @ $0.70 = $2.80 COPY OF  Days Cottage COPY OF Apple Juice 1L (QTY: 4) @ $0.70 = $2.80

Detailed orders breakdown
=========================
Please confirm that you have got this email.
Please send me an invoice for this amount so we can send you payment.
If you need to phone on the day please call 1453840037.

Thanks and best wishes - Stroudco

**Comment by kirstenalarsen** [comment]
It would appear that 'detailed orders breakdown’ has not been done. I understood that our task for this was to code review / bug fix and merge - not necessarily build/enhance feature. How important is this detailed orders breakdown? Can we just remove the title for now and you / someone can come back and do it when resources permit?

and/or we could put a link / message to the appropriate report for them to login and see if they need the detailed breakdown by customer? or something?

**Comment by NickWeir63** [comment]
OK we can live without the detailed orders breakdown on the email but yes it would be great if we could replace the title with something like please login to your account if you need to see a detailed breakdown of this order by customer.
Thanks

**Comment by RohanM** [comment]
Hi @NickWeir63, I've amended that heading, so that part of the email now looks like this:

```
Orders summary
==============

Here is a summary of the orders for your products:

ABC Enterprise 2 Product #1 - 4790 1g (QTY: 2) @ $10.00 = $10.00

Details
=======

For a detailed orders breakdown, please log into your account.
Please confirm that you have received this email.
Please send me an invoice for this amount so we can send you payment.
If you need to phone on the day please call .

Thanks and best wishes - Enterprise 1
```

Does that look good to you? If so, I'll consider this feature ready (as an initial version) and merge this branch.

**Comment by NickWeir63** [comment]
Thanks @RohanM - yes that looks ideal.  Do we close this or move it to backlog?

**Comment by RohanM** [comment]
Note: Some further discussion and simplification in PR #302

**Comment by NickWeir63** [comment]
I just put a test order through staging 2 and then 'notified producers' and the email came through perfectly.  Thanks very much
