### ISSUE TITLE
Roll out v2.0.0

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3692]
@mkllnk summarised what will be the v2 release process [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/3667#issuecomment-479258710) really well:

- [x] - Last v1 release - issue created for v1.30 - #3691
- [x] - Merge 2-0-stable to master
- [x] - Extensive testing and bug fixing
- [x] - Publish 2.0.0-beta pre-release - release notes in #3598
- [x] - Test that release on small instances (Germany, Canada, Katuma).
- [ ] - Observe and fix bugs.
- [x] - Release 2.0.0
- [x] - Carefully deploy to one instance at a time, maybe leaving a couple of days in between to observe errors.
- [x] - Fix bugs and release 2.0.1, 2.0.2,...2.0.42. ;-)
- [x] - Deploy to Australia (3rd most traffic, oldest data)
- [x] - Deploy to UK (2nd most traffic, 2nd oldest data)
- [x] - Deploy to France (most traffic)

**Comment by sauloperez** [comment]
Shall we move this planning to a discourse thread maybe? we should at least rename it to avoid confusion with #3796. They serve different purposes.

**Comment by luisramos0** [comment]
yeah, #3796 is a duplicate of this one. we can close this one now.
roll out conversation is in discourse already: https://community.openfoodnetwork.org/t/ofn-v2-rollout-plan/1619

**Comment by luisramos0** [comment]
we keep this issue to represent the complete roll out of v2.

**Comment by mkllnk** [comment]
France is on today. The maintenance message should be:

> Une maintenance est en cours. Merci de patienter, la plateforme sera bientôt à nouveau disponible. Veuillez nous excuser pour la gêne occasionnée.

**Comment by sauloperez** [comment]
OMG we are gettin closer!

**Comment by lin-d-hop** [comment]
We are soooo close now... GOOOOOO AUSTRALIA!

**Comment by Matt-Yorkley** [comment]
Aus production has been migrated and the few remaining s3's have been moved into the dev ready pipe after this morning's delivery train catchup, so this epic is now officially CLOSED. 

![](https://media.giphy.com/media/QvXe5wq8w94A0/giphy.gif)

**Comment by RachL** [comment]
![ ](https://media.giphy.com/media/bznNJlqAi4pBC/giphy.gif)
