### ISSUE TITLE
Replace all rabl files with AMS serializers

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4060]
### What we should change and why (this is tech debt)
AMS is the way to serialize objects in OFN. We have a few rabl files that need to be converted, time to finish up the [clean up started 5 years ago](https://github.com/openfoodfoundation/openfoodnetwork/issues/280#issuecomment-61745824).

Currently, this is the list of rabl files we have:

- [x] ./app/views/admin/json/_enterprises.rabl #4059 
- [X] ./app/views/json/_order_cycle.rabl #4068
- [X] ./app/views/json/_flash.rabl #4059 
- [X] ./app/views/json/_groups.rabl #4059 
- [X] ./app/views/json/_taxon.rabl #4059 
- [X] ./app/views/json/_hubs.rabl #4059 
- [X] ./app/views/json/_current_user.rabl #4059 
- [X] ./app/views/json/_current_order.rabl #4059 
- [X] ./app/views/json/_enterprises.rabl #4059 
- [X] ./app/views/json/_producers.rabl #4059 
- [X] ./app/views/json/partials/_address.rabl #4059 
- [X] ./app/views/json/partials/_enterprise.rabl #4059 
- [X] ./app/views/json/partials/_hub.rabl #4059 
- [X] ./app/views/json/partials/_producer.rabl #4059 
- [X] ./app/views/json/_producer.rabl #4059 
- [X] ./app/views/spree/admin/variants/search.rabl #4064
- [ ] ./app/views/spree/admin/taxons/search.rabl
- [x] ./app/views/spree/api/variants/bulk_index.v1.rabl #4101
- [x] ./app/views/spree/api/variants/bulk_show.v1.rabl #4101
- [x] ./app/views/spree/api/products/bulk_index.v1.rabl #4101
- [x] ./app/views/spree/api/products/bulk_show.v1.rabl #4101
- [x] ./app/views/spree/api/users/authorise_api.v1.rabl #4111 (now in #4057)
- [x] ./app/views/api/product_images/update_product_image.v1.rabl #4073 
- [x] ./app/views/api/enterprises/bulk_index.v1.rabl #4059 
- [x] ./app/views/api/enterprises/bulk_show.v1.rabl #4101
- [x] ./app/views/api/order_cycles/bulk_index.v1.rabl #4059 
- [x] ./app/views/api/order_cycles/bulk_show.v1.rabl #4059 

### Context
From removing spree_api where we will also need to convert rabl files (from spree_api views) to ams serializers).

### Impact and timeline
We better do this now as part of the api clean up process.

**Comment by luisramos0** [comment]
to close this we are only missing #4101 and #4111 (that is now in #4057)

**Comment by luisramos0** [comment]
meanwhile we added app/views/spree/admin/taxons/search.rabl from spree_backend. So this issue should remain open until no rabl files are present in the codebase.

**Comment by luisramos0** [comment]
I am removing this from api clean up epic.

**Comment by RachL** [comment]
@luisramos0 so where should we move it: dev ready or tech debt backlog?

**Comment by luisramos0** [comment]
ah, sorry, I forgot about that. it's tech debt, we can leave this small change for later. Until spree_backend #4050 is there rabl will work.

**Comment by luisramos0** [comment]
now that spree_backend is going away, when we convert this last rabl view into AMS, I believe we will also be able to remove the rabl dependency itself from our Gemfile.lock:
rabl (0.8.4)
