### ISSUE TITLE
Clean up API

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4071]
### What we should change and why (this is tech debt)
There are currently too many different and inconsistent ways of building API endpoints.
We need to define and use one way of building the API.

The scope of this Epic is:
- [x] remove spree_api, stop using spree_api #4054
- [x] delete all rabl from our project, use ams instead #4060
- [x] move all api endpoints from spree/api to /api #4069
- [x] verify test coverage of currently used API endpoints #4072
- [x] document API exemplar #4070
- [x] finish document API with openAPI #3001 

### Context
From the 2019 global gathering, API is gradually becoming a central part of the OFN strategy.

### Impact and timeline
Some of the business objectives the API will support:
- building external shopfronts
- integration with other systems (POS, other websites, Odoo, etc)
- implement de-centralization of OFN, for example, managing distributed product catalogs
- DATA interoperability
- technological diversity (for example, in terms of frontend dev)

**Comment by luisramos0** [comment]
as part of this epic I created 6 tech debt issues to further clean up the API:
- #4278 Move soft_delete to destroy in both api/products and api/variants
- #4284 Make POST and PUT api endpoints take json data
- #4282 Clean up enterprise images endpoints
- #4283 Remove .json from api/customers endpoint
- #4285 Delete potentially dead api endpoint: taxons_controller#index
- #4279 Clean up api/shipments endpoints

This list is in priority order.
I think I need to include #4278 in this epic because it's something like 2 hours of work and the **deletion** endpoints are very inconsistent right now.

The other 5 issues can wait. although I think we will need to review #4284 soon.

**Comment by luisramos0** [comment]
🎉
