### ISSUE TITLE
[Performance] On /reports/orders&fulfilment

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4131]
## What is the problem we are solving 

This is an epic to capture performance improvements on /reports/orders&fulfilment

## Success factors = expected outcome 

Our performance improvements carry the success metric of:
- Page load and save in 3-5 seconds or less with a shopfront of 10,000 products.

Currently, due to resource constraint, we will not require the performance metrics to be met in order to reprioritise. However the epic will stay open and may move between Performance Backlog and In Dev.

## Implementation Strategy

- [x] Spike: #4130   

- [x] Eager-load: #4308 
- [x] Adding DB Indices: #4318 
- [x] SQL Query for adjustments in Customer Totals report: #4309
- [x] Two calls to fetch customer record for each non-group row in Customer Totals report #4313
- [x] N+1 for shipment, selected shipping rate, and shipping method in Customer Totals report #4314 
- [x] Eager-load associations for variant#options_test #4319

Other issues removed from epic

~~- [ ] Add DB Index for order state: #4317~~

## Link to the Discourse discussion

[https://community.openfoodnetwork.org/t/global-gathering-2019-day-2-performance-action-plan/1651](https://community.openfoodnetwork.org/t/global-gathering-2019-day-2-performance-action-plan/1651)

**Comment by Matt-Yorkley** [comment]
Ok, this epic is done, and the PRs should all be in the next release (v2.6.4). Do we want to do some verifying in production? I'll move it to `test ready` temporarily.

**Comment by lin-d-hop** [comment]
Hey all,
The epic might be done but the UK still has a user that cannot access this report with a 12min timeout for their standard user account.
This account necessarily needs to manage a number of hubs (that share a packing day) and enterprises.
I think we cannot close this epic or the round of performance improvements at this point. To be discussed at the next Delivery Train meeting to discuss next steps.
Sorry for the bad news :-(

**Comment by Matt-Yorkley** [comment]
Ok, I think we need to delve into the use of `OpenFoodNetwork::Permissions` in orders and fulfilment reports, like in #4523

**Comment by luisramos0** [comment]
sorry, I mixed this with OC work, I put this back in test ready.

**Comment by luisramos0** [comment]
I think this is prod-test not dev-test, correct?

**Comment by sauloperez** [comment]
alright, so looking much better but still not good enough in some cases.

![Screenshot from 2020-01-30 19-52-42](https://user-images.githubusercontent.com/762088/73481004-3b2cb900-439b-11ea-8686-b53382297388.png)
_/admin/reports/orders_and_fulfillment_

and there seems to be something specific about the UK, I bet it's just the number of big hubs/usage.

@lin-d-hop claims: 
> I think that is literally one hub running one report

However, I cannot find a way to find out _who_ is that. We'll need to spend some time on providing that information.

**Comment by lin-d-hop** [comment]
I can tell you.
Tamar valley food hubs.
6 years of data to load.
Archiving will help this case!

**Comment by sauloperez** [comment]
:ok_hand:
