### ISSUE TITLE
Update backend payment collection page to use Payment Intents API

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4173]
## What is the problem we are solving

- References #4170 

Setting new credit card info for Stripe payment method should use the Payment Method and Setup Intents API and support SCA. The `off-session` mode would be applicable. (Maybe Payment Intents and `on-session` mode is more appropriate for checkout that will not save the card? Needs to be checked.)

Do this for the following pages:

1. Customer checkout page
2. Customer saved cards page
3. Admin new payment page for order

Support for non-authenticated cards for the following should remain intact and should be tested:

1. Checkout
2. Capturing of payment from admin section
3. Subscriptions

[Gist of Setup Intents](https://stripe.com/docs/api/setup_intents):

> A SetupIntent guides you through the process of setting up a customer's payment credentials for future payments. For example, you could use a SetupIntent to set up your customer's card without immediately collecting a payment.

[Gist of Payment Intents](https://stripe.com/docs/api/payment_intents):

> A PaymentIntent guides you through the process of collecting a payment from your customer. **We recommend that you create exactly one PaymentIntent for each order or customer session in your system.** You can reference the PaymentIntent later to see the history of payment attempts for a particular session.

## Success factors = expected outcome 

**1) Shopper Checkout - The shopper does not wish to save the card:**
For devs: 
- The checkout flow should support SCA if requested from the bank. 
- Use 'on-session' flow.

For testers:
- [ ] Test checkout with a test card that requires SCA - 4000 0025 0000 3155
This card should request an authentication. Stripe will trigger a modal asking for the customer to authenticate.

- [ ] Test checkout with a test card that does not require SCA - 4242 4242 4242 4242
This card should checkout without authentication.

**2) Shopper Checkout - If the shopper DOES wish to save the card** 
For devs:
- SCA is requested and SetupIntent stored every time.
- Use 'off-session' flow.

For testers:
- [ ] Test checkout with a test card that requires SCA - 4000 0025 0000 3155
This card should request an authentication. Stripe will trigger a modal asking for the customer to authenticate.

- [ ] Test checkout with a test card that does not require SCA - 4242 4242 4242 4242
This card should request an authentication. Stripe will trigger a modal asking for the customer to authenticate.

**3) The shopper adds a new saved card in Account -> Cards**
For devs:
- SCA is requested and SetupIntent stored every time.
- Use 'off-session' flow.

For testers:
- [ ] Test checkout with a test card that requires SCA - 4000 0025 0000 3155
This card should request an authentication. Stripe will trigger a modal asking for the customer to authenticate.

- [ ] Test checkout with a test card that does not require SCA - 4242 4242 4242 4242
This card should request an authentication. Stripe will trigger a modal asking for the customer to authenticate.

**4) The admin attempts to make a take a payment in Admin -> Orders -> New Payment**
For devs:
- The checkout flow should support SCA if requested from the bank. 
- To investigate 'on-session' or 'off-session' flow?

For testers:
- [ ] Test checkout with a test card that requires SCA - 4000 0025 0000 3155
This card should request an authentication. Stripe will trigger a modal asking for the customer to authenticate.

- [ ] Test checkout with a test card that does not require SCA - 4242 4242 4242 4242
This card should checkout without authentication.

**5) Standard release testing on Subscriptions specifically using Stripe payments**

- [ ] Release test on subs using stripe

**Comment by lin-d-hop** [comment]
I think we need to figure out the work flow for taking payments by the Admin screen.

Context:
If the bank decides this is a high risk transaction it will request SCA. The Hub manager may decide to get around this by asking the shopper to come and pay in person on collection or another time, meaning they want to be able to do this from the Admin screen with the shopper present.

So in the third case above: Admin new payment page for order :we have two options. We can:
a) give an error in the case of 3D secure auth required such that an admin will just not be able to take payment from here if the bank requests auth.
b) display the 3D secure pop-up regardless, meaning that the hub manager will need the shopper present or able to answer the questions to fill this in. And if they cannot they cancel on the payment.

I think b is a good answer.. However it leaves the question of how to take a payment for an order in the case the someone decides to pay by card AFTER they place the order. I think we need to make sure we have a flow for that.

**Comment by kristinalim** [comment]
Hmm... For #4181 which would support asking customers to authenticate payment for subscriptions with pre-existing saved cards on Stripe, we would already have some code for having a partially captured Stripe payment that still needs SCA authentication.

So, for the third case, maybe we can apply a similar workflow:

1. Admin sets up a partially or fully completed Stripe payment.
2. If only partial and it needs further action, the customer could log in on the website and then click a button where they could then start authenticating the payment if the payment has not yet been voided on the OFN side.
3. Or the admin can do above from the admin section, which is Option B also.

Actually, as far as I understand, we can also email the Stripe link to authenticate the payment straight from the user's inbox. But this flow sounds similar to phishing attempts, and it might be bad to ask users to do this...

**Comment by kristinalim** [comment]
I'm not entirely convinced that you could make this functional without also doing the work for #4180, or if it could be done without wasting a lot of effort on code which would be removed in #4373 

The developer who will work on this issue would find out if #4180 needs to be done in the same PR as this one. :slightly_smiling_face:

**Comment by luisramos0** [comment]
There are 2 parts to this issue:
- update customer account section to use PaymentMethods and SetupIntents: that is now in #4723
- update backend one-off payments collection: that is the only scope of this issue now

#4685 and #4686 already make the admin collection of payments work with the payment intents API. So I am going to mark #4686 as  closing this issue.

We then need to handle further authentications required by communicating with the customer. That will be handled in #4181 (I added this scope to it, we can split that issue later if we want)
