### ISSUE TITLE
Create and integrate PaymentIntent for Stripe payments

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#4180]
## Description

- Related to #4170 

Ongoing and new Stripe payment records should have a Payment Intent set up. This will allow us to handle additional actions, such as customer authentication, if needed for a payment.

Also explore if this should be done at the Order level, but I think this approach would be a lot more complicated considering that we support other payment methods too.

[Gist of Setup Intents](https://stripe.com/docs/api/setup_intents):

> A SetupIntent guides you through the process of setting up a customer's payment credentials for future payments. For example, you could use a SetupIntent to set up your customer's card without immediately collecting a payment.

[Gist of Payment Intents](https://stripe.com/docs/api/payment_intents):

> A PaymentIntent guides you through the process of collecting a payment from your customer. **We recommend that you create exactly one PaymentIntent for each order or customer session in your system.** You can reference the PaymentIntent later to see the history of payment attempts for a particular session.

(Added by @kristinalim on 2019-11-12:)

Not to imply that we create the PaymentIntents even for non-Stripe checkouts/payments. It is more of, if we create a PaymentIntent, do we associate this with the order or the payment record?

For example, if the PaymentIntent is associated with the payment record, if I try to make a failed charge and then have a separate successful charge, these would be under two Stripe PaymentIntent objects.

However, if we have one one PaymentIntent object for each order that would use a Stripe payment, we can then have it recorded on Stripe as:

```
PaymentIntent object (for Order N)
- Payment attempt A
- Partial payment B
- Adjustment payment C
```

## Acceptance Criteria

Each new and ongoing Stripe payment record should have a Payment Intent on Stripe. This stage extends on the work done in #4173  to ensure that OFN is working effectively and efficiently with the Stripe API.

## Success factors = expected outcome 

**1) Shopper Checkout - The shopper does not wish to save the card:**
For devs: 
- The checkout flow should support SCA if requested from the bank. 
- Use 'on-session' flow.

For testers:
- [ ] Test checkout with a test card that requires SCA - 4000 0025 0000 3155
This card should request an authentication. Stripe will trigger a modal asking for the customer to authenticate.

- [ ] Test checkout with a test card that does not require SCA - 4242 4242 4242 4242
This card should checkout without authentication.

**2) Shopper Checkout - If the shopper DOES wish to save the card** 
For devs:
- SCA is requested and SetupIntent stored every time.
- Use 'off-session' flow.

For testers:
- [ ] Test checkout with a test card that requires SCA - 4000 0025 0000 3155
This card should request an authentication. Stripe will trigger a modal asking for the customer to authenticate.

- [ ] Test checkout with a test card that does not require SCA - 4242 4242 4242 4242
This card should request an authentication. Stripe will trigger a modal asking for the customer to authenticate.

**3) The shopper adds a new saved card in Account -> Cards**
For devs:
- SCA is requested and SetupIntent stored every time.
- Use 'off-session' flow.

For testers:
- [ ] Test checkout with a test card that requires SCA - 4000 0025 0000 3155
This card should request an authentication. Stripe will trigger a modal asking for the customer to authenticate.

- [ ] Test checkout with a test card that does not require SCA - 4242 4242 4242 4242
This card should request an authentication. Stripe will trigger a modal asking for the customer to authenticate.

**4) The admin attempts to make a take a payment in Admin -> Orders -> New Payment***
For devs:
- The checkout flow should support SCA if requested from the bank. 
- Use 'on-session' flow.

For testers:
- [ ] Test checkout with a test card that requires SCA - 4000 0025 0000 3155
This card should request an authentication. Stripe will trigger a modal asking for the customer to authenticate.

- [ ] Test checkout with a test card that does not require SCA - 4242 4242 4242 4242
This card should checkout without authentication.

**5) Standard release testing on Subscriptions specifically using Stripe payments**

**Comment by luisramos0** [comment]
I think someone was working for us on the ActiveMerchant side, they support payment intents: https://github.com/activemerchant/active_merchant/pull/3290
I think we need to move from using ActiveMerchant StripeGateway to use this StripePaymentIntentsGateway.

**Comment by luisramos0** [comment]
After issues #4685 and #4686 all payments using the StripeSCA payment method will go through the Payment Intents API. These payments will all go through if there are no extra SCA requirements on the cards used.

What we need to do now is to handle the extra SCA required authentications for specific cards.
This needs to be done in all the places where we charge users.

The ones we can start with are:
- checkout without saving card
- checkout saving card
- add card or authorize card (only after #4723 is done)

There are two other cases:
- subscriptions - triggered automatically
- backoffice payment collection - triggered by the seller
These will be handled in #4181 and #4182 as they will require communicating asynchronously with the customer for further authorizations.

**Comment by luisramos0** [comment]
I am going to close this as the main integration with PaymentIntents is done.
We will need some of these bits to integrate with SetupIntents, I left a comment on https://github.com/openfoodfoundation/openfoodnetwork/issues/4170 so this info is not lost.
