### ISSUE TITLE
Support for Strong Customer Authentication (SCA) in Stripe integration - Part 1

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4211]
### Description
Banks will start declining payments that have not been SCA-authenticated in countries that will require this. We need to start supporting SCA, and thankfully Stripe makes this easy/manageable.

[See migration guidelines here.](https://stripe.com/docs/strong-customer-authentication/migration)

See discussion here #3927 and the articles here.

Issues:

- [x]  Upgrade stripe gem to latest compatible version that supports the Payment Intents and Setup Intents API #4169

- [x]  Update checkout and backend #4173 to use Payment Method and Payment Intents APIs 

- [x] Create and integrate PaymentIntent for Stripe payments #4180

**Comment by luisramos0** [comment]
I am adding the blocked label here just to make it clear this is not in active development.
We will roll out the current solution to as many hubs as possible and collect feedback. After that we will resume this dev effort.

**Comment by luisramos0** [comment]
I cleaned up this epic now. All that is missing here is the improvement of the automated tests of #4639

**Comment by lin-d-hop** [comment]
Now that we have an epic for Stripe Automated Tests #6126 I am closing the epic for SCA Phase One :tada:
