### ISSUE TITLE
Mobile shopping UX improvements

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4531]
## What is the problem we are solving 
The existing shopping experience on mobile is difficult to complete and we assume is a deterrent to shoppers completing the process. This equates to lost sales for our shops in a world where we are more and more likely to use our mobile for shopping online.

We also have many requests from our shops for the mobile experience to be improved, many instances see this as a key feedback item from their customers.

Specific problems in the journey of shopping on mobile are listed [here in Airtable](https://airtable.com/tblPoizwAxVfccvOz/viwIhkyM0Fc83qbts?blocks=hide) and also originally here in a [Google presentation](https://docs.google.com/presentation/d/192oQv86ws5gPXb_biNuoaRKa2j2exu4sY7CUCv3Z3xI/edit?usp=sharing).

## Success factors = expected outcome 

*Users are able to go through the whole shopping journey easily on mobile.*

Metrics we will use to measure this (we need to add specific targets to these, which will require a baseline that @RachL is working on):
- [ ] Increased number of orders via mobile
- [ ] Decreased drop outs / cart abandonment via mobile
- [ ] Improved conversion measure of shop visits > orders place on mobile

...and also potentially: 
- Analytics show that users connecting on mobile and starting to put items in cart don't have a higher drop out rate than users doing that on desktop
- Hub survey show they don't have complains from users who didn't manage to make an order on mobile (we need to understand how many they're getting now to then measure this)

## Useful information and links
**Original community posts:**
- https://community.openfoodnetwork.org/t/mobile-strategy-pt-1-big-wins-progress-now/1367
- https://community.openfoodnetwork.org/t/customers-easily-go-through-the-whole-placing-order-process-on-mobile/1244
- https://community.openfoodnetwork.org/t/customer-mobile-experience/675/8
- https://community.openfoodnetwork.org/t/shopfront-display/676/11

**Discovery and design work links:**
- [Original design thinking](https://docs.google.com/presentation/d/10I8-3mRjxnPUXtEk04X3UERVPEPvqPjrEdF37_1KpmE/edit?usp=sharing) (Google presentation)
- [Finalised designs](https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard) (Zeplin)
- [Original pain points exploration](https://docs.google.com/spreadsheets/d/1Gi5ecw7V2-kKi6IAAn77b8gqDJdZ219RUdPqu-IAOhg/edit?usp=sharing) (Google spreadsheet)

## Work breakdown

We're breaking down this work into releasable sections that deliver sequentially the parts that will solve the biggest problems first. 

These sections are:
- [x] 1. Top header nav
- [x] 2. Global style changes (font, shop logo and name realignment) #4565 and #4566
- [x] 3. Shop content tabs and pages (epic #4567)
- [x] 4. Product listings (epic #4597)
- [x] 5. Order cycle selection (epic #4572)
- [x] 6. Search and filter products (#4601)
- [ ] 7. View cart (header nav dropdown)
- [x] 8. Edit cart - cleanup and colour changes
- [x] 9. Checkout - cleanup and colour changs

 ## Things to think about that will make mobile even better:

- Making the content sing! #2835 has lots of detail on this.
- Implementing maximum characters for single line fields (unit types, titles, etc)
- ...

**Comment by RachL** [comment]
This looks amazing :heart_eyes:

**Comment by daniellemoorhead** [comment]
@mkllnk and @lazabonyi here is the responsive grid layout for you to use for all this work:
https://docs.google.com/presentation/d/10I8-3mRjxnPUXtEk04X3UERVPEPvqPjrEdF37_1KpmE/edit#slide=id.g40ea76c80f_0_18

![image](https://user-images.githubusercontent.com/2911176/46519285-0f8ae300-c8bb-11e8-91d4-18cb9b656140.png)

**Comment by Erioldoesdesign** [comment]
Noting here I'll look at creating a design & research issue in the inception pipe that does some usertesting to confirm these criteria are improving:

 Increased number of orders via mobile
 Decreased drop outs / cart abandonment via mobile
 Improved conversion measure of shop visits > orders place on mobile

**Comment by RachL** [comment]
@Erioldoesdesign as the last issue has been merged, I'm closing here. If needed for follow-up we can recreate some issue in product/design pipe :muscle:
