### ISSUE TITLE
Make OFN independent of spree_backend js, css, fonts and images

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4595]
## Description
This is part of #4050 but it may require more work (or more copy paste from spree to OFN than I initially thought). This issue will be used to make that analysis.

We need to move to OFN anything we need from this folder:
https://github.com/openfoodfoundation/spree/tree/2-0-4-stable/backend/app/assets

The biggest challenge is to find out, in the middle of code that is so old, what is actually required for OFN and what is not...

## Acceptance Criteria & Tests
OFN does not depend on any js, css, fonts or images from spree_backend.

# Analysis
Here I list all the dependencies and flag if they are needed in OFN or not. The checkboxes indicate work done so only the items not needed are ticked in the beginning of this work.
My plan is to copy these dependencies to specific folders in OFN:
- js dependencies to app/vendor/javascript
- css dependencies to app/vendor/stylesheets
- js code to app/assets/javascripts/admin/spree (new folder)
- css code to app/assets/stylesheets/admin/spree (new folder)

### js dependencies
Here we analyze generic JS dependencies.

From admin/spree_backend.js:
- [x] #4607 //= require jquery-migrate-1.0.0 - we can remove this as we already have it through gemfile dep in ofn
- [X] //= require jquery.ui.all - already in OFN, can be ignored
- [x] #4607 //= require modernizr - let's keep it to keep compatibility with very old browsers
- [x] #4611 //= require jquery.cookie - this is used by jstree and jstree is required for taxons admin
- [X] //= require jquery.delayedobserver - this is dead code in spree_backend, can be ignored
- [x] #4611 //= require jquery.jstree/jquery.jstree - this is needed for taxons admin
- [x] #4611 //= require jquery.alerts/jquery.alerts - one usage of jConfirm to confirm a delete of a taxonomy - we should make it a normal confirm and do not copy the dependency to OFN
- [x] #4608 //= require jquery.powertip - this is used to render tooltips in ofn, needs to be copied
- [x] #4614 //= require jquery.vAlign - used to align checkboxes - keep.
- [x] #4607 //= require css_browser_selector_dev - this dep eases the implementation of browser specific tweaks in stylesheets/admin/hacks
- [x] #4614 //= require spin - there are very few situations where this is used - probably easier to keep, we could remove...
- [X] //= require trunk8 - this is dead code in spree_backend - can be ignored
- [X] //= require jquery.adaptivemenu - already in OFN
- [x] #4614 //= require equalize - it equalizes html elements height, it's used in order edit page (order status) and in payments admin for gateway type. We should keep it.
- [x] #4616 //= require responsive-tables - this is used in the orders list html table with class "responsive". we should keep it.
- [x] #4614 //= require jquery.horizontalNav - used in teh main menu. we should keep it.
- [x] #4614 //= require spree - this dep is in spree_core assets so we just need to add the require

and from ./admin:
- [x] #4613 //= require admin/handlebar_extensions - this dep is in spree_core assets so we just need to add the require BUT the file handlebars.js is in spree_backend so we need to move it to ofn

### js code
Here we analyze Spree specific JS files.

From admin/spree_backend.js:
- [x] #4614 //= require admin/spree-select2 - there are two tweaks here: 1. allowClear and 2. product taxons - needs to be tested - maybe not needed

From ./admin.js:
- [x] #4613 //= require admin/variant_autocomplete - I think we need everything except the last two functions (the noop on the ofn directive van be removed afterwards)
- [X] //= require admin/taxon_autocomplete - not needed
- [X] //= require admin/option_type_autocomplete - not needed
- [X] //= require admin/user_picker - not needed, promotions
- [X] //= require admin/product_picker - not needed, promotions

And from the require_tree admin/. above:
- [x] #4613 address_states.js - used in the customer details view. needs to be kept, new folder admin/spree/customer_details
- [X] gateway.js - not needed, not used in OFN view
- [x] #4614 progress.coffee - this works together with spin above, same comment.
- [x] #4614 admin.js.erb - random list of functions, some are needed, some may be deleted
- [ ] #4617 image_settings.js.erb - needed in ofn
- [X] promotions.js - not needed
- [ ] #4617 states.js - used in states page
- [x] #4611 taxon_tree_menu.js.coffee - needed for taxons admin (context menu)
- [ ] #4617 calculator.js - needed for calculator fields
- [x] #4613 shipments.js.erb - needed in order edit page
- [X] stock_management.js.coffee - not needed, we dont have the products/stock view in OFN
- [x] #4611 taxonomy.js.coffee - needed for taxons admin
- [ ] #4617 zone.js.coffee - needed in zones admin
- [ ] #4617 nested-attribute.js - needed in zones admin
- [X] stock_transfer.js.coffee - not needed, we dont have transfers in OFN
- [x] #4613 underscore-min.js - only used in a few places, replace with existing loadsh
- [X] checkouts/edit.js - not applicable to OFN, we have an override
- [x] #4616 images/index.js.coffee - needed when adding images to products
- [x] #4616 images/new.js.coffee - same as above
- [X] orders/edit.js - not needed
- [X] orders/edit_form.js - not needed
- [X] payments/new.js - this code is already in OFN

### CSS dependencies
Here we analyze generic CSS dependencies.

In spree_backend.css:
- [x] #4611 *= require jquery.alerts/jquery.alerts - same as JS above, to be removed
- [x] #4611 *= require jquery.alerts/jquery.alerts.spree - same as previous, to be removed
- [x] #4616 *= require responsive-tables - same as JS dep above, to keep
- [x]  #4620 *= require normalize - it's part of spree_core, we must add the require
- [x]  #4620 *= require skeleton - it's part of spree_core, we must add the require
- [x]  #4620 *= require jquery.ui.datepicker - to keep
- [x] #4608 *= require jquery.powertip - to keep
- [X]  *= require select2 - this is in OFN already

In spree_admin.scss:
- [x] #4620 @import 'globals/functions'; - basic functions, needed
- [x] #4620 @import 'globals/variables'; - colors, needed
- [x] #4620 @import 'globals/mixins'; - border-radius, needed

- [x] #4620 the CSS basics, all needed:
@import 'shared/typography'; 
@import 'shared/tables';
@import 'shared/icons';
@import 'shared/forms';
@import 'shared/layout';

- [x] #4620 These are all needed, we need to copy and remove duplication (some of these rules are repeated in OFN):
@import 'components/states';
@import 'components/actions';
@import 'components/date-picker';
@import 'components/messages';
@import 'components/pagination';
@import 'components/table-filter';
@import 'components/navigation';
@import 'components/sidebar';

- [x] #4614 main progress spinner styling
@import 'components/progress';

- [x] #4613 auto complete specific styling:
@import 'components/product_autocomplete';

- [ ] @import 'plugins/font-awesome'; - ⚠️ Spree has Font Awesome 3.2.1, in OFN head partial we require font-awesome/4.2.0 from a CDN!? see Fonts below
- [x] #4608 @import 'plugins/powertip'; - custom rules, to keep
- [x] #4614 @import 'plugins/select2'; - not the same as the one in OFN, needs to be kept
- [X] @import 'plugins/token-input'; - promotions stuff, not needed
- [x] #4611 @import 'plugins/jstree'; - used in jstree used in taxons admin, see above

- [x] #4607 hacks from css_browser_selector_dev above, to keep
@import 'hacks/mozilla'; 
@import 'hacks/opera';
@import 'hacks/ie';

### CSS
Here we analyze Spree specific CSS files:
- [ ] #4617 @import 'sections/image_settings'; - needed
- [ ] #4616 @import 'sections/orders'; - needed
- [X] @import 'sections/overview'; - not needed
- [ ] #4616 @import 'sections/products'; - only the first 3 rules, not listing_product_stock
- [X] @import 'sections/promotions'; - not needed
- [X] @import 'sections/edit_checkouts'; - not used
- [X] @import 'sections/bulk_transfer'; - not needed

### fonts
- [x] #4628 fontawesome dep, is this needed or can we rely on the CDN call?

### images
Images:
- [x] #4616 credit_card.gif - keep
- [X] payment_banner.png - not used
- [X] progress.gif - I cant find a reference to it, similar to existing spinner
