### ISSUE TITLE
Stripe Test Coverage 2 - Revenge of the Subs

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#6126]
## Description

This epic is for tracking work on the expansion of test coverage for Stripe, following the spike here: #4639.

#### Places users/enterprises interact with Stripe in the platform:
- [x] A - Enterprise Owners/Managers can take payments from backoffice Orders -> Payments #6127 
- [x] B - Shoppers can save cards from Accounts interface - **on hold until phase 2** #6456 and 
#6241 
- [x] C - Shoppers can give permission for enterprises to charge their cards in Accounts interface - **on hold until phase 2** #6456 and 
#6241
- [x] D - Shoppers can buy with cards at Checkout #6050
- [x] E - Shoppers can save cards at Checkout #6130 
- [x] F - Enterprise Owners/Managers can create subscriptions with cards that a shopper has previously saved and given permission for the enterprise to charge from - **on hold until phase 2** #6713 
- [x] G - Enterprise Owners/Manager can refund - partially and fully - credit owning to shoppers. #6127 

#### Additional coverage for Stripe-related behavior:
- [x] H - Stripe authorization redirects at checkout #6124 
- [x] I - Multiple payment attempts at checkout where one fails and another succeeds. Creates multiple payment objects in different states. #6129

**Comment by luisramos0** [comment]
I wonder what needs to be done as part of current prioritized StripeSCA epic.

Maybe now we can cover what's not part of Stripe SCA Part II (integrate with setupIntents, it's prioritized after Rails 4.1 upgrade).
From the list above the following will be changed in Part II:  B, C and F
So, maybe for now, apart from D and H, already done, we cover A, E, G and I
What do you think?

**Comment by luisramos0** [comment]
@Matt-Yorkley I am on to point A and G as part of #6127 feel free to take anything else.

**Comment by Matt-Yorkley** [comment]
So we're delaying B, C and F?

**Comment by luisramos0** [comment]
yes :+1:  B C and F become requirements for StripeSCA part II - this epic: https://github.com/openfoodfoundation/openfoodnetwork/issues/4170

**Comment by luisramos0** [comment]
ok, so this epic can be closed when #6127, #6129 and #6130 are closed :+1:

**Comment by lin-d-hop** [comment]
Perhaps rather than closed it can be taken out of dev ready and put into #4170 ?

**Comment by luisramos0** [comment]
yes, makes sense! thanks.

**Comment by luisramos0** [comment]
ok, all done here. I have put this inside #4170 as agreed. We will pick this up again soon as part of that one. I think we will be moving #4170 to dev ready in the next few days.

**Comment by lin-d-hop** [comment]
@Matt-Yorkley @luisramos0 
Off the top of your heads do you know if linking a Stripe account to OFN is well covered with automated tests?
And the creation of a Stripe payment method?

If not or you would like to Spike to confirm then I can create the issues.
If so, then on the completion of this Epic we can remove Stripe testing from the Release Testing process :tada:

**Comment by andrewpbrett** [comment]
This should now be good to be closed when https://github.com/openfoodfoundation/openfoodnetwork/pull/6713 is merged. #6456 and #6241 took care of B and C and #6713 will take care of F

**Comment by andrewpbrett** [comment]
Closing as #6713 is now merged.
