### ISSUE TITLE
Release v3.3.0

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#6240]
Steps: 

- [x] Include translations: `tx pull --force`
- [x] [Draft new release]
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1819
- [x] Update translations if necessary
- [x] Publish and notify #global-community
- [ ] Deploy and notify #instance-managers
- [ ] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

**Comment by Matt-Yorkley** [comment]
### Update guide for image resizing

Anyone managing an OFN instance should perform these steps to adjust image sizes before deploying this release.

If you've deployed the release already and realised the image sizes need to be updated, skip to **part 2**. :smile:

#### Part 1

Log in as an admin user and go to `https://<your-domain>/admin/image_settings/edit`.

Under "Paperclip Settings" there should be four input fields, and the first two fields for mini and small images should have: `48x48>` and `100x100>`. Change these values to: `48x48#` and `227x227#`. Then scroll down to the bottom and hit the Update button.
![Screenshot from 2020-10-22 22-17-11](https://user-images.githubusercontent.com/9029026/96931307-60c79880-14bd-11eb-866c-bdd6aac68138.png)

#### Part 2

In a terminal, connect to the server via SSH and do the following steps: 

```
ssh openfoodnetwork@<your-domain>
cd apps/openfoodnetwork/current
bundle exec rails console
```
Wait until the console says: `irb(main):001:0>`, and then paste this in (and hit enter):
```ruby
Spree::Image.find_each { |image| image.attachment.reprocess!(:mini, :small) rescue nil }
```

You should see some console output while it's running. When it stops, type `quit` to leave the console.

Done :+1:

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley 

I've tested the release in staging-UK, after the fix about your deploy. All good there for a newly created enterprise and added pics.

https://docs.google.com/document/d/18kZlifPhBhFRQArif_z7QCt1CHZ4RFi3WEbQZ0_X3PM/edit#

However, I'm not entirely sure the transition works smoothly between the previous and the new shopfront.

- in stagin-UK, for a pre-existing hub, the pics look like smaller than they should I think

![image](https://user-images.githubusercontent.com/49817236/97167055-1b85be00-177e-11eb-9fcd-b424c083261b.png)


Also, the pics seem to be missing in pre-existing shops, after following the procedure for resizing windows and your fix #6248:

![image](https://user-images.githubusercontent.com/49817236/97167579-f776ac80-177e-11eb-8731-2ccda005735c.png)

There was a failed staging attempt in this server, so maybe that's the reason. I'll retry the resizing procedure for staging-ES + deploy and report here again in a few mins.

**Comment by lin-d-hop** [comment]
@Matt-Yorkley Did the image resizing tasks happen on staging servers?

**Comment by Matt-Yorkley** [comment]
Looking now :+1:

**Comment by Matt-Yorkley** [comment]
I just followed my steps from the guide again on UK Staging, and it looks good. Images in this shop were not resized, before, and are resized now: https://staging.openfoodnetwork.org.uk/spicy-stuff-hub/shop

There's a few shops that have broken images, but they were broken before :+1:

**Comment by Matt-Yorkley** [comment]
### Going to the Rails console:
![Screenshot from 2020-10-26 11-45-15](https://user-images.githubusercontent.com/9029026/97169590-95bc3f80-178a-11eb-9d8e-58bd134da8db.png)
### Pasting in the resizing command:
![Screenshot from 2020-10-26 11-45-27](https://user-images.githubusercontent.com/9029026/97169602-99e85d00-178a-11eb-90d0-9fd8b03bb6ab.png)
### After resizing has finished:
![Screenshot from 2020-10-26 11-45-54](https://user-images.githubusercontent.com/9029026/97169607-9a80f380-178a-11eb-96d1-8ffb690e1788.png)

**Comment by filipefurtad0** [comment]
I just double-checked this on staging-ES as well:

**Before resizing/deploy**:

![image](https://user-images.githubusercontent.com/49817236/97169651-4bcf5b80-1782-11eb-9a44-8ba9e4a9d411.png)


**After resizing/deploy**:

![image](https://user-images.githubusercontent.com/49817236/97169682-5a1d7780-1782-11eb-8c0e-a6156632fc4d.png)

I think we are good here!

**Comment by filipefurtad0** [comment]
There is a tiny issue shopfront issue, which affects only:
- mobile
- items with prices in EUR
- prices with 4 digits

See below, left side - staging-UK / right side staging-ES

![image](https://user-images.githubusercontent.com/49817236/97171007-9baf2200-1784-11eb-8428-34e278901e96.png)

I wouldn't say this is a blocker and will proceed to open an issue on this but pinging you @Matt-Yorkley @RachL @lin-d-hop for awereness.

**Comment by kabhotz** [comment]
Dear Matt, I'm trying to reproduce your steps on my staging environment and at part 2 I have this error:

`Command :: file -b --mime '/tmp/gallette20201031-2264-bx761f20201031-2264-1d1752x'
[paperclip] Error while determining content type: Cocaine::CommandNotFoundError
Command :: identify -format %m '/tmp/gallette20201031-2264-bx761f.jpg[0]'
Command :: identify -format %m '/tmp/gallette20201031-2264-bx761f.jpg[0]'
Command :: identify -format %m '/tmp/gallette20201031-2264-bx761f.jpg[0]'
Command :: convert -auto-orient '/tmp/gallette20201031-2264-bx761f.jpg[0]' -auto-orient -resize "x227" -crop "227x227+4+0" +repage -strip -auto-orient -colorspace RGB '/tmp/gallette20201031-2264-bx761f20201031-2264-1pt157o'
Command :: file -b --mime '/tmp/gallette20201031-2264-bx761f20201031-2264-1pt157o'
[paperclip] Error while determining content type: Cocaine::CommandNotFoundError
[paperclip] deleting /home/openfoodnetwork/apps/openfoodnetwork/releases-old/2020-10-22-000312/public/spree/products/384/mini/gallette.jpg
[paperclip] deleting /home/openfoodnetwork/apps/openfoodnetwork/releases-old/2020-10-22-000312/public/spree/products/384/small/gallette.jpg
[paperclip] Saving attachments.
Command :: identify -format %m '/tmp/mais_marano20201031-2264-qefrbf.jpg[0]'
Command :: identify -format %m '/tmp/mais_marano20201031-2264-qefrbf.jpg[0]'
Command :: identify -format %m '/tmp/mais_marano20201031-2264-qefrbf.jpg[0]'
Command :: convert -auto-orient '/tmp/mais_marano20201031-2264-qefrbf.jpg[0]' -auto-orient -resize "x48" -crop "48x48+33+0" +repage -strip -auto-orient -colorspace RGB '/tmp/mais_marano20201031-2264-qefrbf20201031-2264-1vyp2g1'
Command :: file -b --mime '/tmp/mais_marano20201031-2264-qefrbf20201031-2264-1vyp2g1'
[paperclip] Error while determining content type: Cocaine::CommandNotFoundError
Command :: identify -format %m '/tmp/mais_marano20201031-2264-qefrbf.jpg[0]'
Command :: identify -format %m '/tmp/mais_marano20201031-2264-qefrbf.jpg[0]'
Command :: identify -format %m '/tmp/mais_marano20201031-2264-qefrbf.jpg[0]'
Command :: convert -auto-orient '/tmp/mais_marano20201031-2264-qefrbf.jpg[0]' -auto-orient -resize "x227" -crop "227x227+158+0" +repage -strip -auto-orient -colorspace RGB '/tmp/mais_marano20201031-2264-qefrbf20201031-2264-1x8qbql'
Command :: file -b --mime '/tmp/mais_marano20201031-2264-qefrbf20201031-2264-1x8qbql'
[paperclip] Error while determining content type: Cocaine::CommandNotFoundError
[paperclip] deleting /home/openfoodnetwork/apps/openfoodnetwork/releases-old/2020-10-22-000312/public/spree/products/385/mini/mais_marano.jpg
[paperclip] deleting /home/openfoodnetwork/apps/openfoodnetwork/releases-old/2020-10-22-000312/public/spree/products/385/small/mais_marano.jpg
[paperclip] Saving attachments.
Command :: identify -format %m '/tmp/indexcasrastagne20201031-2264-1uuor54.jpg[0]'
Command :: identify -format %m '/tmp/indexcasrastagne20201031-2264-1uuor54.jpg[0]'
Command :: identify -format %m '/tmp/indexcasrastagne20201031-2264-1uuor54.jpg[0]'
Command :: convert -auto-orient '/tmp/indexcasrastagne20201031-2264-1uuor54.jpg[0]' -auto-orient -resize "x48" -crop "48x48+11+0" +repage -strip -auto-orient -colorspace RGB '/tmp/indexcasrastagne20201031-2264-1uuor5420201031-2264-167njhn'
Command :: file -b --mime '/tmp/indexcasrastagne20201031-2264-1uuor5420201031-2264-167njhn'
[paperclip] Error while determining content type: Cocaine::CommandNotFoundError
Command :: identify -format %m '/tmp/indexcasrastagne20201031-2264-1uuor54.jpg[0]'
Command :: identify -format %m '/tmp/indexcasrastagne20201031-2264-1uuor54.jpg[0]'
Command :: identify -format %m '/tmp/indexcasrastagne20201031-2264-1uuor54.jpg[0]'
Command :: convert -auto-orient '/tmp/indexcasrastagne20201031-2264-1uuor54.jpg[0]' -auto-orient -resize "x227" -crop "227x227+55+0" +repage -strip -auto-orient -colorspace RGB '/tmp/indexcasrastagne20201031-2264-1uuor5420201031-2264-2kfje1'
Command :: file -b --mime '/tmp/indexcasrastagne20201031-2264-1uuor5420201031-2264-2kfje1'
[paperclip] Error while determining content type: Cocaine::CommandNotFoundError
[paperclip] deleting /home/openfoodnetwork/apps/openfoodnetwork/releases-old/2020-10-22-000312/public/spree/products/386/mini/indexcasrastagne.jpg
[paperclip] deleting /home/openfoodnetwork/apps/openfoodnetwork/releases-old/2020-10-22-000312/public/spree/products/386/small/indexcasrastagne.jpg
[paperclip] Saving attachments.
=> nil`

Seems there is a missing command.
Thanks in advance!
David

**Comment by kabhotz** [comment]
Problem solved with the installation of file command on Ubuntu 18.04:

`sudo apt-get install -y file`
