### ISSUE TITLE
Adjustment updates

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#6402]
### What we should change and why (this is tech debt)

Adjustments are the cause of lots of pain points in various places. In Spree 2.2 there was a big overhaul of adjustments that reduced the performance issues and made things easier to calculate. We can backport those changes, but it'll be a fairly big job.

### Context

Lots of deadlocks on cart updates due to adjustments, performance issues, etc.

### Impact and timeline

Big impact, no idea of timeline.

### Notes

Related reading:
- Release notes: https://guides.spreecommerce.org/release_notes/2_2_0.html#adjustments-refactoring
- Article explaining it all in depth: https://ryanbigg.com/2013/09/order-adjustments
- The actual Pull Request: https://github.com/spree/spree/pull/3567

### Gameplan

In no particular order;

- [x] Carefully backport all the relevant changes from the Spree 2.2 adjustments PR into OFN
- [x] Backport relevant Spree spec changes, and pull in some additional Spree unit tests where useful
- [x] Do some additional clean up and cut any bits we don't need
- [x] Adapt any remaining bits in our codebase to the new changes
- [x] Deal with any changes needed in Spree-related views that display adjustments
- [x] Adapt Enterprise Fees to the new adjustments setup
- [x] Finish adpapting all relevant OFN specs
- [x] Handle migrations for existing data where the data model has changed slightly
- [x] Backport API controllers for the new adjustments and any related changes to existing API controllers

**Comment by tschumilas** [comment]
Not sure if this is one of the adjustments this epic might look at?    https://community.openfoodnetwork.org/t/adjustments-when-taxes-are-excluded-from-prices/2133

**Comment by Matt-Yorkley** [comment]
@tschumilas this epic is about making some underlying technical changes, we're not doing any wishlist items at the moment. The changes are quite large though, and they might impact the way taxes can be calculated, hopefully making ti easier in the future.

**Comment by tschumilas** [comment]
All good - thanks @Matt-Yorkley

**Comment by Matt-Yorkley** [comment]
### Polymorphic associations

The three polymorphic associations on the Adjustment model (`adjustable`, `source` and `originator`) have been stripped down to two (`adjustable` and `source`), and a direct association to `order` has been added. This makes the data model a lot simpler. So; an adjustment record always has an `order_id`, and it also has a `source` (eg a `TaxRate`) and an `adjustable` (eg a `LineItem`). 

The inverse of the direct association to an `order` means that `order.adjustments` will return all of the adjustments that are relevant to an order, regardless of whether they are tax adjustments for line_items or adjustments related to shipping methods, etc.

### Persisting totals

The following schema changes have been added:

- `spree_orders` now has `shipment_total` and `tax_total` columns
- `spree_line_items` now has `adjustment_total` and `tax_total` columns
- `spree_shipments` now has `adjustment_total` and `tax_total` columns

This means that these values can be persisted in a simpler way on each record when they are created or updated, and they can subsequently be fetched directly without querying and re-computing everything.

**Comment by Matt-Yorkley** [comment]
Note to self: this commit from 2017 needs looking at https://github.com/openfoodfoundation/openfoodnetwork/commit/2d2792225a607a06dbd06aab694030a5cfa04d95#diff-7e5462a3bd9c8321c204cfba2377a185494da02b4e6dbef00763416a9957398aR7

The associations added here probably need to be deleted.

**Comment by Matt-Yorkley** [comment]
Ditto this PR and linked issues: https://github.com/openfoodfoundation/openfoodnetwork/pull/3229/files

:fire:
