### ISSUE TITLE
Allow shoppers to compare unit prices

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/openfoodnetwork#6449]
## What is the problem we are solving

Users would like to quickly compare the price of different products across different sizes/variants (possibly producers), displaying the price per unit (kg,l,oz,lbs..) enables them to determine which product offers the best value.

The need for this feature came up because legislation requires to display the price per unit in

- Europe:  [https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:31998L0006&from=EN](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:31998L0006&from=EN)

- Australia: [https://www.accc.gov.au/business/industry-codes/unit-pricing-code](https://www.accc.gov.au/business/industry-codes/unit-pricing-code)
- UK: [https://www2.oxfordshire.gov.uk/cms/sites/default/files/folders/documents/business/tradingstandards/PriceMarkingofGoods.pdf](https://www2.oxfordshire.gov.uk/cms/sites/default/files/folders/documents/business/tradingstandards/PriceMarkingofGoods.pdf)

**Link to Discourse:** https://community.openfoodnetwork.org/t/display-price-per-unit-on-variants/1712

Currently hubs and producers who have a shop on the OFN add this in the description field, but it is not clear enough for the buyer and there are cases where the workaround does not work.

Since the legal requirements are different depending on the country, but this information is valuable from a (shopper) user perspective **we will display the unit price for all instances** for simplicity, even if it may not be legally required for some instances.

### This Epic inlcudes

**Enterprise User | Admin**

- allow enterprise user to add the price per unit (weight or volume) to their product
- explain enterprise user why this price is needed (tooltip)
- for all existing products unit prices should be added automatically
- allow enterprise users to have different unit prices for different customers (for example restaurants are usually buying larger quantities and paying a lower unit price than B2C customers)

**Shopper | Shopfront**

- Display unit prices clearly visible to shoppers on product list page

**Are there different versions?**

V1: In the most simple solution, the unit price will automatically be calculated when the enterprise user creates a product. The enterprise will not be able to edit the unit price when creating a product nor to hide it on the shopfront.

V2 (Possibly): 

- Enterprise users could be users be enabled to choose, if they do not want to display unit prices (e.g. instances where it is not required by law)
- Enterprise users could be enabled to adjust their unit prices (e.g. user sees that their price per kg is too high or low and/or they rather want the define the unit prices and calculate item price based on this), this will affect the price of the item and vice versa

### Acceptance Criteria

These should be tested for both new products and already existing products

**Shopper Side**

- [ ] The unit price is displayed on
    - [ ]  on the product list page
    - [ ]  cart page, checkout pages
- [ ]  The unit price reflects the final price (including all taxes and fees)

**Enterprise Side**

- [ ]  The Unit Price is displayed when creating products, for product variants (bulk edit page) and /inventory
- [ ]  If enterprise user (=shop/hub) is using the product list only, display unit price from product list
- [ ]  If enterprise user (=shop/hub) is using inventory to create a different price,
display unit price from product inventory (because the inventory unit
price overwrites the product list unit price )
- [ ]  if the enterprise user is a **reseller** (buy and sell a product with a markup) the **unit price** of the product **should adjust to the new price including the markup**
- [ ]  if the enterprise user **sells distribution services** (they don’t add a markup but they invoice a service fee, on top of the original price of the product from the producer) the **unit price should not** change.
- [ ]  The unit price reflects the price of the shop, not the unit price of the original product (variant) in the product list
- [ ]  The design we come up with needs to work with the new product list designs (shopper facing) currently underway, both mobile ([openfoodfoundation/openfoodnetwork#4597](https://github.com/openfoodfoundation/openfoodnetwork/issues/4597)) & desktop
- [ ]  for enterprise users that show different unit prices to different customers, the unit price is should be correctly calculated taking into account tag, fee or inventory overrides

- [ ] **CSV Import**: When importing CSV, the Unit Price has to be automatically calculated based on the item price (AC tech only, no implications for design

Edit: (Dec 21st)
As a high level rule for simplicity, : only on **shopper side** the unit price needs to be displayed including taxes **+ fees**, at the various places where it is displayed on Admin side, **no fees** need to be displayed (but VAT/GST depending on if the instance selected ‘tax inclusive price’,) 

### Open Tasks / Questions

- [x] Doublecheck legal requirements

- [x] Are there other parts of the product that might be affected?

- [x] Anything else needed for design?

**Questions?** (Edited: after discussion with @RachL , added here to have all info in one place

- Australia requires unit price per 100 ml/g, whereas Europe & UK per 1kg/l → shall we go for simplicity and have per 1kg/l for all instances to start with? _-> _Y_ES_. Taking into account the additional info on Australia for fruit and vegetables, which are commonly sold by weight, see in comments)__

**Shopper Side**
- should the unit price be displayed only on product list page or also other places (cart page, checkout pages, order confirmation notifications) _-> for consistency and bc helpful for the user to compare prices let’s include unit prices on cart page and checkout page as well (if that fits the designs, to be checked by @Erioldoesdesign )_

**Enterprise Side**

- should enterprise users be enabled to choose, if they do not want to display unit prices (e.g. instances where it is not required by law? _-> This is potentially for a V2_
- should enterprise users be enabled to adjust their unit prices (e.g. user sees that their price per kg is too high or low and/or they rather want the define the unit prices and calculate item price based on this) _-> This is potentially for a V2_
- If Enterprise users have different unit prices for different customers (for example restaurants are usually buying larger quantities and paying a lower unit price than B2C customers) _-> as different prices are not visible to each consumer, but managed by using inventory or variants & tagging, no implications for design here_
- should unit prices be added as a (as a static for V1)  column on [admin/products page](https://www.openfoodnetwork.org.uk/admin/products) and [admin/products/variants page ](https://www.openfoodnetwork.org.uk/admin/products/tomatoes2/variants) ? _-> YES, to all of them, bc that’s actually useful to enterprise users for doublechecking if unit price are correct for different variants (implications for design @Erioldoesdesign )_

### Design Indications

Unit pricing information must be:

- prominent—it must stand out so that it is easily seen
- proximate—it must be positioned close to the selling price for the grocery item
- legible—it must not be difficult to read
- unambiguous—the information must be accurate and its meaning clear.

### Design Figma file:

Back-office: https://www.figma.com/file/JipdbYxaWxDN5i7L1coniF/Unit-Prices-Cleaned-for-dev-pipe?node-id=0%3A1
Front-office (including mobile): https://www.figma.com/file/EPKyXwl5VDQaw8IBHalCEZ/Unit-Prices?node-id=0%3A1

**Comment by Matt-Yorkley** [comment]
I left a comment in this issue, but it's relevant to the whole epic: https://github.com/openfoodfoundation/openfoodnetwork/issues/6495#issuecomment-763044319
