### ISSUE TITLE
As an enterprise manager, I can use a new date picker

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6664]
## Description
**- As a:** Enterprise user and super admin
**- On pages:** 
Our date picker are used in the following pages:

- `/admin/order_cycles` on ordercycle list but also when creating / editing an order cycle
- `/admin/reports` on each reports filters
- `/admin/orders?q[s]=completed_at+desc` in start / end date filters
- `/admin/orders/bulk_management` in start / end date filters
- `/admin/subscriptions/` when creating or editing a new subscription

**- I want to be able to do:** use a date picker that is not using `jquery-ui-rails` as a dependency

This new date picker must:

✅ Select both date and time
✅ Is already or can be translated
✅ Allow the option in the future to add custom shortcuts such “next month” (as discussed [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/5032#issuecomment-625757174))
✔️ Currently the date picker has the option to select NOW/TODAY. It could be nice to keep it.
✔️ Only if super easy with the new one, it would be nice to improve the selection of the end date. Currently let's say I want to select a time between January the 21st to January the 22nd I have to select:
`2021-01-21 00:00` to `2021-01-23 00:00`.
Selecting the **23**rd ensures that the 22nd is fully selected. So for the end date it's important that if I select the 22 date, it actually does cover the 22nd completely automatically.
However for the start date, the current behavior (starting at midnight) is correct.

Legend: 
✅ : Must have
✔️ : Nice to have

## Acceptance Criteria & Tests

See description for must have criterias, plus:

_Scenario 1 As a simple producer_

We need to make sure selecting dates ends up with correct results on all the following pages:

- `/admin/order_cycles` on ordercycle list but also when creating / editing an order cycle
- `/admin/reports` on each reports filters
- `/admin/orders?q[s]=completed_at+desc` in start / end date filters
- `/admin/orders/bulk_management` in start / end date filters
- `/admin/subscriptions/` when creating or editing a new subscription

_Scenario 2 As a multi-producer hub_

Repeat same tests as scenario 1

_Scenario 3 As a super admin_

Repeat same tests as scenario 2

## Previous discussions

https://github.com/openfoodfoundation/openfoodnetwork/pull/6482

Especially this comment has all the history: https://github.com/openfoodfoundation/openfoodnetwork/pull/6482#issuecomment-758102380

## Todo
- [x] Implements datetimepicker at each location where it is used
- [x] Remove every reference to jQueryUI Datetimepicker
- [x] Transforme each "start date - end date" to a Daterangepicker (see example: https://flatpickr.js.org/examples/#range-calendar ; and comment https://github.com/openfoodfoundation/openfoodnetwork/issues/6664#issuecomment-760964353) --> opened a new issue : #6730
- [x] Add shortcut such as "Now" or "next month"
- [x] Apply small css modifications (see comment https://github.com/openfoodfoundation/openfoodnetwork/issues/6664#issuecomment-760369452) if it's easy. If not, open new issue to customize widget.

**Comment by RachL** [comment]
@jibees in the "what should be tested" section of your PR, don't hesitate to adapt the criterias I've listed according to the "nice to have" that will really be possible with the new one.

**Comment by jibees** [comment]
Dears @openfoodfoundation/train-drivers-product-owners, let me introduce you the new datetimepicker : https://flatpickr.js.org/ and its integration inside our product: 
<img width="1009" alt="Capture d’écran 2021-01-14 à 16 55 59" src="https://user-images.githubusercontent.com/296452/104615287-64685700-5689-11eb-8295-7f9e163b46d1.png">

I wonder if it's necessary to customize the design of this component to better match our design? With absolutely no effort, we can apply a different theme, that you can see here: https://flatpickr.js.org/themes/ Of course, with more effort we can customize. 
What do you think?

**Comment by RachL** [comment]
For myself I don't think I have a preference. As changing the template seems easy, it's also something we can do in iteration 2 or when we work on other UI bits of the admin. I wouldn't customize anything ourselves at this stage.

One comment on the AM/PM system: it made me realize that currently we have the 24 hours mode included for all instances. 

As this seems configurable with this date picker, maybe we will want to create an issue in order for instance managers to be able to configure this in their general instance settings. If it's not too complex. Otherwise I guess we must forget this comment :)

Also @jibees the date format in the field seems weird?  Maybe you've noticed already ;-)
![image](https://user-images.githubusercontent.com/6525576/104617443-bad69500-568b-11eb-9b1e-7ce8676c97bb.png)

**Comment by jibees** [comment]
>  Also @jibees the date format in the field seems weird? Maybe you've noticed already ;-)

Yes, this is the very beginning, and there are a lot of bugs, but I wanted to show you the datetimepicker early to have this kind of discussions about design and/or UX.

**Comment by Erioldoesdesign** [comment]
Firstly, I read 'Native DateTime Input' and 'mobile' support and I am so happy!!!! 😄 

re. styling we're kind of in the process of doing a UI uplift piece in the product list part of OFN that I can take you through in our chat catch up.

Generally theres a few things I can list here that'll align with the UI uplift more:

- Remove the rounded corners
- The blue circle behind the selected number can be our brand highlighted blue: #5498DA
- In the material_blue theme the header behind the month is changed. We can also make this #5498DA to indicate a selectable/click area for both the month and year. The Mon-Sun text can then change to our brand dark text colour #121212

I'm a little concerned some click hit areas are small - for the drop down month and year select this is a very 'precise' mouse click so (as always) I'm worried about accessibility! 

But this is an improvement so we can consider accessibility improvements at a later date when we can focus on that subject 👍 

great work JB!

**Comment by jibees** [comment]
Dears @openfoodfoundation/train-drivers-product-owners, I've a bunch of questions (which may concerns only the ` admin/order_cycles` page, but this is where I am now 😉): 
 - Previously, the input was "editable with keyboard" (as the user type the date, with cursor) and there was a small icon beside when clicking on it opens the datetimepicker (see the screenshot). Is it something you want to keep?
 
<img width="282" alt="Capture d’écran 2021-01-15 à 11 15 25" src="https://user-images.githubusercontent.com/296452/104712592-01c39980-5723-11eb-9c81-59f1468f3058.png">
The default behavior with flatpickrjs is a non-editable input and clicking on it directly opens the widget (you can see the basic example here: https://flatpickr.js.org/examples/#basic)

  - Is it normal behaviour to select a date in the past for order_cycle?

**Comment by RachL** [comment]
> Is it something you want to keep?

I think it lead to mistakes. I used it once to copy-paste a date, but that was because the hour selector was not working. IMO if the selector works smoothly, editing the field is not necessary. @Erioldoesdesign is there a case where editing the field is an accessibility best pratice?

> Is it normal behaviour to select a date in the past for order_cycle?

I'm afraid this is used quite often to quickly open an order cycle if you don't have the NOW option. Also I don't know if this questions applies to the date picker in the reports, but overthere a past date needs to be selected all the time.

**Comment by jibees** [comment]
In the page `admin/orders` there is a date range picker which is actually composed with two datepicker. I assume it can be possible to use the flatpickr widget with the date range option (as shown here: https://flatpickr.js.org/examples/#range-calendar)
Obviously, this is more work, but I think it makes sense.

**Comment by RachL** [comment]
@jibees fro muser point of vue, the most important is to be able to select a date range. So if it's easier to do it with one datepicker only go for it.

**Comment by jibees** [comment]
Currently, selecting a new date on `/admin/order_cycles/` (and maybe elsewhere), change the time to `00:00` whatever the previous hour was. Is it a behavior we want to keep or having the preselecting hour the same as the previous is a more accurate behavior?

**Comment by RachL** [comment]
@jibees what do you mean by "previous hour" ? The current hour?

Especially when filtering order or reports, it's important that the dates get "included" but maybe it's easier if we call each other quickly on this one :)

**Comment by jibees** [comment]
@Erioldoesdesign, I've made some of the customizations you've suggested. 
Here it is: 
<img width="336" alt="Capture d’écran 2021-01-20 à 16 02 43" src="https://user-images.githubusercontent.com/296452/105193711-147e0a00-5b39-11eb-8c65-0fa28864e844.png">
Tell me if you agree with that, or perhaps if there is something to add.

**Comment by Erioldoesdesign** [comment]
@jibees looks good to me!

At some point in the future, we'll look at the colours used in the back office admin side and the front end shopper side and see if colours need to match or not.

for your info (you may already know) I got this link from Maikel re. the front end shop colours: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/stylesheets/darkswarm/branding.scss
