### ISSUE TITLE
[Reports] Enterprise Fees with Tax Report

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#6815]
## What is the problem we are solving 

As an enterprise I need to be able to understand:

- A breakdown of fees per producer
- A breakdown of fees per order
- How much tax I am taking on different kinds of fees
- How much tax I need to pay on to my (tax registered) producers
- How much I need to pay directly to government

Currently OFN reports do not offer this data. Tax is aggregated in order totals and it difficult to disaggregate through queries directly.

This problem is significant for all tax registered enterprises.

## Success factors = expected outcome 

- [ ]  A new report for Enterprise Fees w Tax
- [ ]  The ability to view this report sorted by order and by producer
- [ ]  The ability to show or hide totals rows in the report
- [ ]  The ability to download the report as a CSV
- [ ]  In the UI figures should be rounded to 2 decimal places. In CSVs figures should be rounded to 6 decimal places.
- [ ]  The ability to filter the results based on a range of inputs
- [ ] User guide is updated
- [ ] Data is queriable over v1 of the API

EDIT
Adding specific API criteria as @Matt-Yorkley has now found the API task to be a simple one and the product team have agreed to make tax reports the first officially supported API endpoints.

## Link to the "Product Development - Backlog" item in Discourse
https://community.openfoodnetwork.org/t/ui-data-tax-reporting/2134
