### ISSUE TITLE
Enterprise users can manually create customers for their shop

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#850]
http://community.openfoodnetwork.org/t/wholesale-and-tagging/505/14

Estimate = 3 days

**Comment by mkllnk** [comment]
From Rob's description:

Allow enterprise users to manually create customers for their hub (without that customer necessarily having to place an order with the hub first)
  - Routing, views, controller actions for creating customers
  - Logic around what to do when a user with the given email does not yet exist
    - Add the customer anyway, so that tags can be added
    - (Optionally?) Send an email to the address provided, suggesting they create an account
    - Associate customer with user when it is created?
        - what is the benefit of this?

**Comment by mkllnk** [comment]
**Roadmap**

- [ ] "Add customer" button on `/admin/customers`
- [ ] input field allows to enter an email address
- [ ] there is no auto-complete to protect private email addresses
- [ ] an indicator shows whether a user with the entered email address exists

**Open questions**

*What to do when a user with the given email does not yet exist?*

We could offer an "Invite customer" button. It creates the customer and you can tag it already. An invitation email is sent to the email address. If that user signs up, it has to be associated with the customer entry. Customer entries without user should be greyed out in the customer list.

*What happens to customer entries that never get associated?*

If an invited user never signs up, their email address is still in the system. It could be the managers responsibility to keep that list clean. We could delete old entries after a given time period.

*Is there potential for abuse?*

Someone could use this feature to invite lots of desired customers. We should include a statement in the invitation email to write to abuse@openfoodnetwork.example if they didn't want to receive that email.

**Comment by daniellemoorhead** [comment]
@mkllnk these open questions you've posted - what was decided in the session last week, and therefore what was built for customers that aren't existing OFN users? And did you get the UK guys to look at this during testing?

**Comment by mkllnk** [comment]
@daniellemoorhead The open questions are not implemented. They are a nice-to-have. I would wait for people to request these features before we invest more time in them. It would probably be good to gain some experiences with the current version as well. The current version was tested by Sally and is in production. The UK people are very welcome to look at this, @pmackay, @lin-d-hop, @stveep. I spent around 12 hours on this. You can review the changes here: https://github.com/openfoodfoundation/openfoodnetwork/compare/f15e948...49febc?expand=1 (A pull request would have been easier to review, sorry.)

**Comment by daniellemoorhead** [comment]
@NickWeir63 @lin-d-hop @Rocksj let us know if you need some help when reviewing this or if it's evident how to use it. You can see above on here that @mkllnk has listed out the items that were delivered in the roadmap, so that should be a start for you to play around with the feature.

**Comment by NickWeir63** [comment]
Thanks @mkllnk this worked fine for me.  The only minor issue was that when I clicked 'update' I didn't get a message saying it had updated - the screen just stayed the same - but when I left this screen the new customer had been created successfu
![screenshot 2016-04-19 11 07 13](https://cloud.githubusercontent.com/assets/10517702/14635740/afa102cc-061f-11e6-9c5f-dd516fa752c8.png)
lly.

**Comment by mkllnk** [comment]
Yes, that's an old issue of that page. We could create a new issue "Customers page improvements" and schedule that for next sprint.

**Comment by mkllnk** [comment]
@NickWeir63 Is it right that you were missing feedback about updates, but not about creation? If that's correct, @bingxie and @oeoeaio are working on that already.

**Comment by NickWeir63** [comment]
Yes @mkllnk that is correct - I didn't get any acknowledgment when I clicked update but the new customer did create successfully
