### ISSUE TITLE
User email verification

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#946]
At the moment users do not have to verify/confirm their email address to become an OFN user, we want to change this so that they do need to go through a confirmation process to ensure that they are using their own email address.

Check this google doc to see the overarching flows for initial sign up and then for unconfirmed users trying to login: https://docs.google.com/document/d/1S9CDFQZZr8BLeMfzgDQAHM8ZpPGOc_WjC1vgNm-T23M/edit

Question: Should unconfirmed user login issues be done first, followed by the sign up issues?

**Comment by mkllnk** [comment]
This issue is evaluating #833.

- [ ] Create an initial overview and estimates (1)
- [ ] Change the user model to have confirmable email addresses (2)
- [ ] Change user registration process to prompt for email validation (4)
- [ ] Change enterprise user registration to prompt for email validation (3)
- [ ] Change Discourse login to check for confirmed user email address (2)
- [ ] Replace `enterprise.email` by `enterprise.contact` which is a user (3)
- [ ] Prevent guests from using a registered email address (4)
- [ ] Associate guest orders of same email address after validation, #917 and #907 (2)

Estimate: 21 hours

@sstead: Does this change make #948 obsolete?

**Comment by sstead** [comment]
Yes, i think so. I don't think a user who has >1 enterprise permission needs to validate every enterprise they create anymore. Also with the new 'contact only' email field, there's not the problem of disengaged OFN users needing to confirm an email just for it to show on a profile. These were the main reasons why we once wanted to be able to manually verify emails. I think the plan above, of requiring each user to confirm an email is less likely to create situations were people don't verify their email, and superadmin would need to do it for them.

**Comment by myriamboure** [comment]
@daniellemoorhead to move forward on the email validation, I have started to write down how I see that functionnaly given all the inputs and comments in various discussions on community and Github. I put it here on Discourse https://community.openfoodnetwork.org/t/confirmation-emails-registration-flow/237/3?u=myriamboure as we are still on the functional level, I propose facilitate the discussion there first, and when we agree on the process then move back here to specify the tech part (which I might not be super useful for...)
Ping @ltrls if you want to have a look at what we are talking about... when we get the feedback from the community we can see how we can break this down maybe.

**Comment by daniellemoorhead** [comment]
Hey @sigmundpetersen I moved this back to "all the things" because we don't put epics into the zenhub delivery pipe. They're tracked on the feature backlog here: https://github.com/openfoodfoundation/openfoodnetwork/projects/19

**Comment by sigmundpetersen** [comment]
Roger that! 👍

**Comment by myriamboure** [comment]
We had no problem reported since the feature has been released, so we can consider it as done and I'm now closing the epic :-)
